// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [55:0] out_V_TDATA;
output   out_V_TVALID;
input  [63:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] icmp_ln249_fu_346_p2;
wire   [0:0] icmp_ln253_fu_352_p2;
reg    ap_predicate_op53_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln249_reg_2834;
wire   [0:0] icmp_ln249_reg_2834_pp0_iter0_reg;
reg   [0:0] icmp_ln290_reg_3002;
reg    ap_predicate_op463_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
wire   [2:0] trunc_ln257_fu_409_p1;
reg   [63:0] W_packed_V_reg_2846;
wire   [0:0] icmp_ln272_fu_457_p2;
reg   [0:0] icmp_ln272_reg_2858;
reg   [0:0] p_Result_5_reg_2870;
wire   [1:0] add_ln840_1_fu_683_p2;
reg   [1:0] add_ln840_1_reg_2882;
wire   [1:0] add_ln840_3_fu_689_p2;
reg   [1:0] add_ln840_3_reg_2887;
wire   [1:0] add_ln840_5_fu_701_p2;
reg   [1:0] add_ln840_5_reg_2892;
wire   [1:0] add_ln840_9_fu_875_p2;
reg   [1:0] add_ln840_9_reg_2897;
wire   [1:0] add_ln840_11_fu_881_p2;
reg   [1:0] add_ln840_11_reg_2902;
wire   [1:0] add_ln840_13_fu_893_p2;
reg   [1:0] add_ln840_13_reg_2907;
wire   [1:0] add_ln840_17_fu_1067_p2;
reg   [1:0] add_ln840_17_reg_2912;
wire   [1:0] add_ln840_19_fu_1073_p2;
reg   [1:0] add_ln840_19_reg_2917;
wire   [1:0] add_ln840_21_fu_1085_p2;
reg   [1:0] add_ln840_21_reg_2922;
wire   [1:0] add_ln840_25_fu_1259_p2;
reg   [1:0] add_ln840_25_reg_2927;
wire   [1:0] add_ln840_27_fu_1265_p2;
reg   [1:0] add_ln840_27_reg_2932;
wire   [1:0] add_ln840_29_fu_1277_p2;
reg   [1:0] add_ln840_29_reg_2937;
wire   [1:0] add_ln840_33_fu_1451_p2;
reg   [1:0] add_ln840_33_reg_2942;
wire   [1:0] add_ln840_35_fu_1457_p2;
reg   [1:0] add_ln840_35_reg_2947;
wire   [1:0] add_ln840_37_fu_1469_p2;
reg   [1:0] add_ln840_37_reg_2952;
wire   [1:0] add_ln840_41_fu_1643_p2;
reg   [1:0] add_ln840_41_reg_2957;
wire   [1:0] add_ln840_43_fu_1649_p2;
reg   [1:0] add_ln840_43_reg_2962;
wire   [1:0] add_ln840_45_fu_1661_p2;
reg   [1:0] add_ln840_45_reg_2967;
wire   [1:0] add_ln840_49_fu_1835_p2;
reg   [1:0] add_ln840_49_reg_2972;
wire   [1:0] add_ln840_51_fu_1841_p2;
reg   [1:0] add_ln840_51_reg_2977;
wire   [1:0] add_ln840_53_fu_1853_p2;
reg   [1:0] add_ln840_53_reg_2982;
wire   [1:0] add_ln840_57_fu_2027_p2;
reg   [1:0] add_ln840_57_reg_2987;
wire   [1:0] add_ln840_59_fu_2033_p2;
reg   [1:0] add_ln840_59_reg_2992;
wire   [1:0] add_ln840_61_fu_2045_p2;
reg   [1:0] add_ln840_61_reg_2997;
wire   [0:0] icmp_ln290_fu_2057_p2;
reg   [7:0] ap_phi_mux_inElem_1_phi_fu_288_p18;
wire   [7:0] ap_phi_reg_pp0_iter0_inElem_1_reg_285;
wire   [7:0] tmp_fu_386_p10;
reg   [31:0] sf_fu_190;
wire   [31:0] sf_2_fu_2051_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [6:0] i_fu_194;
wire   [6:0] i_2_fu_340_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [6:0] add_i_i_i2_776138_fu_198;
wire   [6:0] add_ln840_7_fu_2236_p2;
reg   [6:0] add_i_i_i2_1_7140_fu_202;
wire   [6:0] add_ln840_15_fu_2295_p2;
reg   [6:0] add_i_i_i2_2_7142_fu_206;
wire   [6:0] add_ln840_23_fu_2354_p2;
reg   [6:0] add_i_i_i2_3_7144_fu_210;
wire   [6:0] add_ln840_31_fu_2413_p2;
reg   [6:0] add_i_i_i2_4_7146_fu_214;
wire   [6:0] add_ln840_39_fu_2472_p2;
reg   [6:0] add_i_i_i2_5_7148_fu_218;
wire   [6:0] add_ln840_47_fu_2531_p2;
reg   [6:0] add_i_i_i2_6_7150_fu_222;
wire   [6:0] add_ln840_55_fu_2590_p2;
reg   [6:0] add_i_i_i2_7_7152_fu_226;
wire   [6:0] add_ln840_63_fu_2649_p2;
reg   [7:0] inputBuf_V_fu_230;
reg   [7:0] inputBuf_V_1_fu_234;
reg   [7:0] inputBuf_V_2_fu_238;
reg   [7:0] inputBuf_V_3_fu_242;
reg   [7:0] inputBuf_V_4_fu_246;
reg   [7:0] inputBuf_V_5_fu_250;
reg   [7:0] inputBuf_V_6_fu_254;
reg   [7:0] inputBuf_V_7_fu_258;
reg   [31:0] nf_fu_262;
wire   [31:0] nf_5_fu_2080_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [2:0] tmp_fu_386_p9;
wire   [0:0] p_Result_s_fu_453_p1;
wire   [0:0] local_temp_V_fu_463_p1;
wire   [0:0] xor_ln1019_fu_515_p2;
wire   [0:0] xor_ln1019_1_fu_521_p2;
wire   [0:0] local_temp_V_1_fu_467_p3;
wire   [0:0] xor_ln1019_2_fu_539_p2;
wire   [0:0] p_Result_1_fu_531_p3;
wire   [0:0] xor_ln1019_3_fu_545_p2;
wire   [0:0] p_Result_2_fu_555_p3;
wire   [0:0] local_temp_V_2_fu_475_p3;
wire   [0:0] xor_ln1019_4_fu_563_p2;
wire   [0:0] xor_ln1019_5_fu_569_p2;
wire   [0:0] p_Result_3_fu_579_p3;
wire   [0:0] local_temp_V_3_fu_483_p3;
wire   [0:0] xor_ln1019_6_fu_587_p2;
wire   [0:0] xor_ln1019_7_fu_593_p2;
wire   [0:0] p_Result_4_fu_603_p3;
wire   [0:0] local_temp_V_4_fu_491_p3;
wire   [0:0] xor_ln1019_8_fu_611_p2;
wire   [0:0] xor_ln1019_9_fu_617_p2;
wire   [0:0] p_Result_6_fu_635_p3;
wire   [0:0] local_temp_V_6_fu_499_p3;
wire   [0:0] xor_ln1019_12_fu_643_p2;
wire   [0:0] xor_ln1019_13_fu_649_p2;
wire   [0:0] p_Result_7_fu_659_p3;
wire   [0:0] local_temp_V_7_fu_507_p3;
wire   [0:0] xor_ln1019_14_fu_667_p2;
wire   [0:0] xor_ln1019_15_fu_673_p2;
wire   [1:0] zext_ln780_5_fu_655_p1;
wire   [1:0] zext_ln780_4_fu_623_p1;
wire   [1:0] zext_ln780_3_fu_599_p1;
wire   [1:0] zext_ln780_fu_527_p1;
wire   [1:0] zext_ln780_1_fu_551_p1;
wire   [1:0] zext_ln840_1_fu_679_p1;
wire   [1:0] add_ln840_4_fu_695_p2;
wire   [1:0] zext_ln780_2_fu_575_p1;
wire   [0:0] local_temp_V_8_fu_707_p3;
wire   [0:0] xor_ln1019_16_fu_763_p2;
wire   [0:0] xor_ln1019_17_fu_769_p2;
wire   [0:0] local_temp_V_9_fu_715_p3;
wire   [0:0] xor_ln1019_18_fu_779_p2;
wire   [0:0] xor_ln1019_19_fu_785_p2;
wire   [0:0] local_temp_V_10_fu_723_p3;
wire   [0:0] xor_ln1019_20_fu_795_p2;
wire   [0:0] xor_ln1019_21_fu_801_p2;
wire   [0:0] local_temp_V_11_fu_731_p3;
wire   [0:0] xor_ln1019_22_fu_811_p2;
wire   [0:0] xor_ln1019_23_fu_817_p2;
wire   [0:0] local_temp_V_12_fu_739_p3;
wire   [0:0] xor_ln1019_24_fu_827_p2;
wire   [0:0] xor_ln1019_25_fu_833_p2;
wire   [0:0] local_temp_V_14_fu_747_p3;
wire   [0:0] xor_ln1019_28_fu_843_p2;
wire   [0:0] xor_ln1019_29_fu_849_p2;
wire   [0:0] local_temp_V_15_fu_755_p3;
wire   [0:0] xor_ln1019_30_fu_859_p2;
wire   [0:0] xor_ln1019_31_fu_865_p2;
wire   [1:0] zext_ln1019_5_fu_855_p1;
wire   [1:0] zext_ln1019_4_fu_839_p1;
wire   [1:0] zext_ln1019_3_fu_823_p1;
wire   [1:0] zext_ln1019_fu_775_p1;
wire   [1:0] zext_ln1019_1_fu_791_p1;
wire   [1:0] zext_ln840_7_fu_871_p1;
wire   [1:0] add_ln840_12_fu_887_p2;
wire   [1:0] zext_ln1019_2_fu_807_p1;
wire   [0:0] local_temp_V_16_fu_899_p3;
wire   [0:0] xor_ln1019_32_fu_955_p2;
wire   [0:0] xor_ln1019_33_fu_961_p2;
wire   [0:0] local_temp_V_17_fu_907_p3;
wire   [0:0] xor_ln1019_34_fu_971_p2;
wire   [0:0] xor_ln1019_35_fu_977_p2;
wire   [0:0] local_temp_V_18_fu_915_p3;
wire   [0:0] xor_ln1019_36_fu_987_p2;
wire   [0:0] xor_ln1019_37_fu_993_p2;
wire   [0:0] local_temp_V_19_fu_923_p3;
wire   [0:0] xor_ln1019_38_fu_1003_p2;
wire   [0:0] xor_ln1019_39_fu_1009_p2;
wire   [0:0] local_temp_V_20_fu_931_p3;
wire   [0:0] xor_ln1019_40_fu_1019_p2;
wire   [0:0] xor_ln1019_41_fu_1025_p2;
wire   [0:0] local_temp_V_22_fu_939_p3;
wire   [0:0] xor_ln1019_44_fu_1035_p2;
wire   [0:0] xor_ln1019_45_fu_1041_p2;
wire   [0:0] local_temp_V_23_fu_947_p3;
wire   [0:0] xor_ln1019_46_fu_1051_p2;
wire   [0:0] xor_ln1019_47_fu_1057_p2;
wire   [1:0] zext_ln1019_11_fu_1047_p1;
wire   [1:0] zext_ln1019_10_fu_1031_p1;
wire   [1:0] zext_ln1019_9_fu_1015_p1;
wire   [1:0] zext_ln1019_6_fu_967_p1;
wire   [1:0] zext_ln1019_7_fu_983_p1;
wire   [1:0] zext_ln840_13_fu_1063_p1;
wire   [1:0] add_ln840_20_fu_1079_p2;
wire   [1:0] zext_ln1019_8_fu_999_p1;
wire   [0:0] local_temp_V_24_fu_1091_p3;
wire   [0:0] xor_ln1019_48_fu_1147_p2;
wire   [0:0] xor_ln1019_49_fu_1153_p2;
wire   [0:0] local_temp_V_25_fu_1099_p3;
wire   [0:0] xor_ln1019_50_fu_1163_p2;
wire   [0:0] xor_ln1019_51_fu_1169_p2;
wire   [0:0] local_temp_V_26_fu_1107_p3;
wire   [0:0] xor_ln1019_52_fu_1179_p2;
wire   [0:0] xor_ln1019_53_fu_1185_p2;
wire   [0:0] local_temp_V_27_fu_1115_p3;
wire   [0:0] xor_ln1019_54_fu_1195_p2;
wire   [0:0] xor_ln1019_55_fu_1201_p2;
wire   [0:0] local_temp_V_28_fu_1123_p3;
wire   [0:0] xor_ln1019_56_fu_1211_p2;
wire   [0:0] xor_ln1019_57_fu_1217_p2;
wire   [0:0] local_temp_V_30_fu_1131_p3;
wire   [0:0] xor_ln1019_60_fu_1227_p2;
wire   [0:0] xor_ln1019_61_fu_1233_p2;
wire   [0:0] local_temp_V_31_fu_1139_p3;
wire   [0:0] xor_ln1019_62_fu_1243_p2;
wire   [0:0] xor_ln1019_63_fu_1249_p2;
wire   [1:0] zext_ln1019_17_fu_1239_p1;
wire   [1:0] zext_ln1019_16_fu_1223_p1;
wire   [1:0] zext_ln1019_15_fu_1207_p1;
wire   [1:0] zext_ln1019_12_fu_1159_p1;
wire   [1:0] zext_ln1019_13_fu_1175_p1;
wire   [1:0] zext_ln840_19_fu_1255_p1;
wire   [1:0] add_ln840_28_fu_1271_p2;
wire   [1:0] zext_ln1019_14_fu_1191_p1;
wire   [0:0] local_temp_V_32_fu_1283_p3;
wire   [0:0] xor_ln1019_64_fu_1339_p2;
wire   [0:0] xor_ln1019_65_fu_1345_p2;
wire   [0:0] local_temp_V_33_fu_1291_p3;
wire   [0:0] xor_ln1019_66_fu_1355_p2;
wire   [0:0] xor_ln1019_67_fu_1361_p2;
wire   [0:0] local_temp_V_34_fu_1299_p3;
wire   [0:0] xor_ln1019_68_fu_1371_p2;
wire   [0:0] xor_ln1019_69_fu_1377_p2;
wire   [0:0] local_temp_V_35_fu_1307_p3;
wire   [0:0] xor_ln1019_70_fu_1387_p2;
wire   [0:0] xor_ln1019_71_fu_1393_p2;
wire   [0:0] local_temp_V_36_fu_1315_p3;
wire   [0:0] xor_ln1019_72_fu_1403_p2;
wire   [0:0] xor_ln1019_73_fu_1409_p2;
wire   [0:0] local_temp_V_38_fu_1323_p3;
wire   [0:0] xor_ln1019_76_fu_1419_p2;
wire   [0:0] xor_ln1019_77_fu_1425_p2;
wire   [0:0] local_temp_V_39_fu_1331_p3;
wire   [0:0] xor_ln1019_78_fu_1435_p2;
wire   [0:0] xor_ln1019_79_fu_1441_p2;
wire   [1:0] zext_ln1019_23_fu_1431_p1;
wire   [1:0] zext_ln1019_22_fu_1415_p1;
wire   [1:0] zext_ln1019_21_fu_1399_p1;
wire   [1:0] zext_ln1019_18_fu_1351_p1;
wire   [1:0] zext_ln1019_19_fu_1367_p1;
wire   [1:0] zext_ln840_25_fu_1447_p1;
wire   [1:0] add_ln840_36_fu_1463_p2;
wire   [1:0] zext_ln1019_20_fu_1383_p1;
wire   [0:0] local_temp_V_40_fu_1475_p3;
wire   [0:0] xor_ln1019_80_fu_1531_p2;
wire   [0:0] xor_ln1019_81_fu_1537_p2;
wire   [0:0] local_temp_V_41_fu_1483_p3;
wire   [0:0] xor_ln1019_82_fu_1547_p2;
wire   [0:0] xor_ln1019_83_fu_1553_p2;
wire   [0:0] local_temp_V_42_fu_1491_p3;
wire   [0:0] xor_ln1019_84_fu_1563_p2;
wire   [0:0] xor_ln1019_85_fu_1569_p2;
wire   [0:0] local_temp_V_43_fu_1499_p3;
wire   [0:0] xor_ln1019_86_fu_1579_p2;
wire   [0:0] xor_ln1019_87_fu_1585_p2;
wire   [0:0] local_temp_V_44_fu_1507_p3;
wire   [0:0] xor_ln1019_88_fu_1595_p2;
wire   [0:0] xor_ln1019_89_fu_1601_p2;
wire   [0:0] local_temp_V_46_fu_1515_p3;
wire   [0:0] xor_ln1019_92_fu_1611_p2;
wire   [0:0] xor_ln1019_93_fu_1617_p2;
wire   [0:0] local_temp_V_47_fu_1523_p3;
wire   [0:0] xor_ln1019_94_fu_1627_p2;
wire   [0:0] xor_ln1019_95_fu_1633_p2;
wire   [1:0] zext_ln1019_29_fu_1623_p1;
wire   [1:0] zext_ln1019_28_fu_1607_p1;
wire   [1:0] zext_ln1019_27_fu_1591_p1;
wire   [1:0] zext_ln1019_24_fu_1543_p1;
wire   [1:0] zext_ln1019_25_fu_1559_p1;
wire   [1:0] zext_ln840_31_fu_1639_p1;
wire   [1:0] add_ln840_44_fu_1655_p2;
wire   [1:0] zext_ln1019_26_fu_1575_p1;
wire   [0:0] local_temp_V_48_fu_1667_p3;
wire   [0:0] xor_ln1019_96_fu_1723_p2;
wire   [0:0] xor_ln1019_97_fu_1729_p2;
wire   [0:0] local_temp_V_49_fu_1675_p3;
wire   [0:0] xor_ln1019_98_fu_1739_p2;
wire   [0:0] xor_ln1019_99_fu_1745_p2;
wire   [0:0] local_temp_V_50_fu_1683_p3;
wire   [0:0] xor_ln1019_100_fu_1755_p2;
wire   [0:0] xor_ln1019_101_fu_1761_p2;
wire   [0:0] local_temp_V_51_fu_1691_p3;
wire   [0:0] xor_ln1019_102_fu_1771_p2;
wire   [0:0] xor_ln1019_103_fu_1777_p2;
wire   [0:0] local_temp_V_52_fu_1699_p3;
wire   [0:0] xor_ln1019_104_fu_1787_p2;
wire   [0:0] xor_ln1019_105_fu_1793_p2;
wire   [0:0] local_temp_V_54_fu_1707_p3;
wire   [0:0] xor_ln1019_108_fu_1803_p2;
wire   [0:0] xor_ln1019_109_fu_1809_p2;
wire   [0:0] local_temp_V_55_fu_1715_p3;
wire   [0:0] xor_ln1019_110_fu_1819_p2;
wire   [0:0] xor_ln1019_111_fu_1825_p2;
wire   [1:0] zext_ln1019_35_fu_1815_p1;
wire   [1:0] zext_ln1019_34_fu_1799_p1;
wire   [1:0] zext_ln1019_33_fu_1783_p1;
wire   [1:0] zext_ln1019_30_fu_1735_p1;
wire   [1:0] zext_ln1019_31_fu_1751_p1;
wire   [1:0] zext_ln840_37_fu_1831_p1;
wire   [1:0] add_ln840_52_fu_1847_p2;
wire   [1:0] zext_ln1019_32_fu_1767_p1;
wire   [0:0] local_temp_V_56_fu_1859_p3;
wire   [0:0] xor_ln1019_112_fu_1915_p2;
wire   [0:0] xor_ln1019_113_fu_1921_p2;
wire   [0:0] local_temp_V_57_fu_1867_p3;
wire   [0:0] xor_ln1019_114_fu_1931_p2;
wire   [0:0] xor_ln1019_115_fu_1937_p2;
wire   [0:0] local_temp_V_58_fu_1875_p3;
wire   [0:0] xor_ln1019_116_fu_1947_p2;
wire   [0:0] xor_ln1019_117_fu_1953_p2;
wire   [0:0] local_temp_V_59_fu_1883_p3;
wire   [0:0] xor_ln1019_118_fu_1963_p2;
wire   [0:0] xor_ln1019_119_fu_1969_p2;
wire   [0:0] local_temp_V_60_fu_1891_p3;
wire   [0:0] xor_ln1019_120_fu_1979_p2;
wire   [0:0] xor_ln1019_121_fu_1985_p2;
wire   [0:0] local_temp_V_62_fu_1899_p3;
wire   [0:0] xor_ln1019_124_fu_1995_p2;
wire   [0:0] xor_ln1019_125_fu_2001_p2;
wire   [0:0] local_temp_V_63_fu_1907_p3;
wire   [0:0] xor_ln1019_126_fu_2011_p2;
wire   [0:0] xor_ln1019_127_fu_2017_p2;
wire   [1:0] zext_ln1019_41_fu_2007_p1;
wire   [1:0] zext_ln1019_40_fu_1991_p1;
wire   [1:0] zext_ln1019_39_fu_1975_p1;
wire   [1:0] zext_ln1019_36_fu_1927_p1;
wire   [1:0] zext_ln1019_37_fu_1943_p1;
wire   [1:0] zext_ln840_43_fu_2023_p1;
wire   [1:0] add_ln840_60_fu_2039_p2;
wire   [1:0] zext_ln1019_38_fu_1959_p1;
wire   [31:0] nf_4_fu_2068_p2;
wire   [0:0] icmp_ln302_fu_2074_p2;
wire   [0:0] local_temp_V_5_fu_2183_p3;
wire   [0:0] xor_ln1019_10_fu_2190_p2;
wire   [0:0] xor_ln1019_11_fu_2195_p2;
wire   [6:0] select_ln272_7_fu_2176_p3;
wire   [6:0] zext_ln840_fu_2201_p1;
wire   [6:0] zext_ln840_2_fu_2211_p1;
wire   [6:0] add_ln840_fu_2205_p2;
wire   [2:0] zext_ln840_4_fu_2223_p1;
wire   [2:0] zext_ln840_3_fu_2220_p1;
wire   [2:0] add_ln840_6_fu_2226_p2;
wire   [6:0] zext_ln840_5_fu_2232_p1;
wire   [6:0] add_ln840_2_fu_2214_p2;
wire   [0:0] local_temp_V_13_fu_2242_p3;
wire   [0:0] xor_ln1019_26_fu_2249_p2;
wire   [0:0] xor_ln1019_27_fu_2254_p2;
wire   [6:0] select_ln272_6_fu_2169_p3;
wire   [6:0] zext_ln840_6_fu_2260_p1;
wire   [6:0] zext_ln840_8_fu_2270_p1;
wire   [6:0] add_ln840_8_fu_2264_p2;
wire   [2:0] zext_ln840_10_fu_2282_p1;
wire   [2:0] zext_ln840_9_fu_2279_p1;
wire   [2:0] add_ln840_14_fu_2285_p2;
wire   [6:0] zext_ln840_11_fu_2291_p1;
wire   [6:0] add_ln840_10_fu_2273_p2;
wire   [0:0] local_temp_V_21_fu_2301_p3;
wire   [0:0] xor_ln1019_42_fu_2308_p2;
wire   [0:0] xor_ln1019_43_fu_2313_p2;
wire   [6:0] select_ln272_5_fu_2162_p3;
wire   [6:0] zext_ln840_12_fu_2319_p1;
wire   [6:0] zext_ln840_14_fu_2329_p1;
wire   [6:0] add_ln840_16_fu_2323_p2;
wire   [2:0] zext_ln840_16_fu_2341_p1;
wire   [2:0] zext_ln840_15_fu_2338_p1;
wire   [2:0] add_ln840_22_fu_2344_p2;
wire   [6:0] zext_ln840_17_fu_2350_p1;
wire   [6:0] add_ln840_18_fu_2332_p2;
wire   [0:0] local_temp_V_29_fu_2360_p3;
wire   [0:0] xor_ln1019_58_fu_2367_p2;
wire   [0:0] xor_ln1019_59_fu_2372_p2;
wire   [6:0] select_ln272_4_fu_2155_p3;
wire   [6:0] zext_ln840_18_fu_2378_p1;
wire   [6:0] zext_ln840_20_fu_2388_p1;
wire   [6:0] add_ln840_24_fu_2382_p2;
wire   [2:0] zext_ln840_22_fu_2400_p1;
wire   [2:0] zext_ln840_21_fu_2397_p1;
wire   [2:0] add_ln840_30_fu_2403_p2;
wire   [6:0] zext_ln840_23_fu_2409_p1;
wire   [6:0] add_ln840_26_fu_2391_p2;
wire   [0:0] local_temp_V_37_fu_2419_p3;
wire   [0:0] xor_ln1019_74_fu_2426_p2;
wire   [0:0] xor_ln1019_75_fu_2431_p2;
wire   [6:0] select_ln272_3_fu_2148_p3;
wire   [6:0] zext_ln840_24_fu_2437_p1;
wire   [6:0] zext_ln840_26_fu_2447_p1;
wire   [6:0] add_ln840_32_fu_2441_p2;
wire   [2:0] zext_ln840_28_fu_2459_p1;
wire   [2:0] zext_ln840_27_fu_2456_p1;
wire   [2:0] add_ln840_38_fu_2462_p2;
wire   [6:0] zext_ln840_29_fu_2468_p1;
wire   [6:0] add_ln840_34_fu_2450_p2;
wire   [0:0] local_temp_V_45_fu_2478_p3;
wire   [0:0] xor_ln1019_90_fu_2485_p2;
wire   [0:0] xor_ln1019_91_fu_2490_p2;
wire   [6:0] select_ln272_2_fu_2141_p3;
wire   [6:0] zext_ln840_30_fu_2496_p1;
wire   [6:0] zext_ln840_32_fu_2506_p1;
wire   [6:0] add_ln840_40_fu_2500_p2;
wire   [2:0] zext_ln840_34_fu_2518_p1;
wire   [2:0] zext_ln840_33_fu_2515_p1;
wire   [2:0] add_ln840_46_fu_2521_p2;
wire   [6:0] zext_ln840_35_fu_2527_p1;
wire   [6:0] add_ln840_42_fu_2509_p2;
wire   [0:0] local_temp_V_53_fu_2537_p3;
wire   [0:0] xor_ln1019_106_fu_2544_p2;
wire   [0:0] xor_ln1019_107_fu_2549_p2;
wire   [6:0] select_ln272_1_fu_2134_p3;
wire   [6:0] zext_ln840_36_fu_2555_p1;
wire   [6:0] zext_ln840_38_fu_2565_p1;
wire   [6:0] add_ln840_48_fu_2559_p2;
wire   [2:0] zext_ln840_40_fu_2577_p1;
wire   [2:0] zext_ln840_39_fu_2574_p1;
wire   [2:0] add_ln840_54_fu_2580_p2;
wire   [6:0] zext_ln840_41_fu_2586_p1;
wire   [6:0] add_ln840_50_fu_2568_p2;
wire   [0:0] local_temp_V_61_fu_2596_p3;
wire   [0:0] xor_ln1019_122_fu_2603_p2;
wire   [0:0] xor_ln1019_123_fu_2608_p2;
wire   [6:0] select_ln272_fu_2127_p3;
wire   [6:0] zext_ln840_42_fu_2614_p1;
wire   [6:0] zext_ln840_44_fu_2624_p1;
wire   [6:0] add_ln840_56_fu_2618_p2;
wire   [2:0] zext_ln840_46_fu_2636_p1;
wire   [2:0] zext_ln840_45_fu_2633_p1;
wire   [2:0] add_ln840_62_fu_2639_p2;
wire   [6:0] zext_ln840_47_fu_2645_p1;
wire   [6:0] add_ln840_58_fu_2627_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_start_int;
reg    ap_condition_1923;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_1_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U1(
    .din0(inputBuf_V_fu_230),
    .din1(inputBuf_V_1_fu_234),
    .din2(inputBuf_V_2_fu_238),
    .din3(inputBuf_V_3_fu_242),
    .din4(inputBuf_V_4_fu_246),
    .din5(inputBuf_V_5_fu_250),
    .din6(inputBuf_V_6_fu_254),
    .din7(inputBuf_V_7_fu_258),
    .din8(tmp_fu_386_p9),
    .dout(tmp_fu_386_p10)
);

MatrixVectorActivation_1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1923)) begin
        if ((icmp_ln249_fu_346_p2 == 1'd0)) begin
            i_fu_194 <= i_2_fu_340_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_194 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1923)) begin
        if (((icmp_ln249_fu_346_p2 == 1'd0) & (icmp_ln290_fu_2057_p2 == 1'd1))) begin
            nf_fu_262 <= nf_5_fu_2080_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_262 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1923)) begin
        if (((icmp_ln249_fu_346_p2 == 1'd0) & (icmp_ln290_fu_2057_p2 == 1'd1))) begin
            sf_fu_190 <= 32'd0;
        end else if (((icmp_ln249_fu_346_p2 == 1'd0) & (icmp_ln290_fu_2057_p2 == 1'd0))) begin
            sf_fu_190 <= sf_2_fu_2051_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_190 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        W_packed_V_reg_2846 <= weights_V_TDATA;
        add_ln840_11_reg_2902 <= add_ln840_11_fu_881_p2;
        add_ln840_13_reg_2907 <= add_ln840_13_fu_893_p2;
        add_ln840_17_reg_2912 <= add_ln840_17_fu_1067_p2;
        add_ln840_19_reg_2917 <= add_ln840_19_fu_1073_p2;
        add_ln840_1_reg_2882 <= add_ln840_1_fu_683_p2;
        add_ln840_21_reg_2922 <= add_ln840_21_fu_1085_p2;
        add_ln840_25_reg_2927 <= add_ln840_25_fu_1259_p2;
        add_ln840_27_reg_2932 <= add_ln840_27_fu_1265_p2;
        add_ln840_29_reg_2937 <= add_ln840_29_fu_1277_p2;
        add_ln840_33_reg_2942 <= add_ln840_33_fu_1451_p2;
        add_ln840_35_reg_2947 <= add_ln840_35_fu_1457_p2;
        add_ln840_37_reg_2952 <= add_ln840_37_fu_1469_p2;
        add_ln840_3_reg_2887 <= add_ln840_3_fu_689_p2;
        add_ln840_41_reg_2957 <= add_ln840_41_fu_1643_p2;
        add_ln840_43_reg_2962 <= add_ln840_43_fu_1649_p2;
        add_ln840_45_reg_2967 <= add_ln840_45_fu_1661_p2;
        add_ln840_49_reg_2972 <= add_ln840_49_fu_1835_p2;
        add_ln840_51_reg_2977 <= add_ln840_51_fu_1841_p2;
        add_ln840_53_reg_2982 <= add_ln840_53_fu_1853_p2;
        add_ln840_57_reg_2987 <= add_ln840_57_fu_2027_p2;
        add_ln840_59_reg_2992 <= add_ln840_59_fu_2033_p2;
        add_ln840_5_reg_2892 <= add_ln840_5_fu_701_p2;
        add_ln840_61_reg_2997 <= add_ln840_61_fu_2045_p2;
        add_ln840_9_reg_2897 <= add_ln840_9_fu_875_p2;
        icmp_ln272_reg_2858 <= icmp_ln272_fu_457_p2;
        icmp_ln290_reg_3002 <= icmp_ln290_fu_2057_p2;
        p_Result_5_reg_2870 <= ap_phi_mux_inElem_1_phi_fu_288_p18[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_2834 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_i_i_i2_1_7140_fu_202 <= add_ln840_15_fu_2295_p2;
        add_i_i_i2_2_7142_fu_206 <= add_ln840_23_fu_2354_p2;
        add_i_i_i2_3_7144_fu_210 <= add_ln840_31_fu_2413_p2;
        add_i_i_i2_4_7146_fu_214 <= add_ln840_39_fu_2472_p2;
        add_i_i_i2_5_7148_fu_218 <= add_ln840_47_fu_2531_p2;
        add_i_i_i2_6_7150_fu_222 <= add_ln840_55_fu_2590_p2;
        add_i_i_i2_776138_fu_198 <= add_ln840_7_fu_2236_p2;
        add_i_i_i2_7_7152_fu_226 <= add_ln840_63_fu_2649_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln249_reg_2834 <= icmp_ln249_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd1))) begin
        inputBuf_V_1_fu_234 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd2))) begin
        inputBuf_V_2_fu_238 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd3))) begin
        inputBuf_V_3_fu_242 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd4))) begin
        inputBuf_V_4_fu_246 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd5))) begin
        inputBuf_V_5_fu_250 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd6))) begin
        inputBuf_V_6_fu_254 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd7))) begin
        inputBuf_V_7_fu_258 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_409_p1 == 3'd0))) begin
        inputBuf_V_fu_230 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_346_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_352_p2 == 1'd0) & (icmp_ln249_fu_346_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_288_p18 = tmp_fu_386_p10;
    end else if ((((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd6)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd0)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd1)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd2)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd3)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd4)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd5)) | ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0) & (trunc_ln257_fu_409_p1 == 3'd7)))) begin
        ap_phi_mux_inElem_1_phi_fu_288_p18 = in0_V_TDATA;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_288_p18 = ap_phi_reg_pp0_iter0_inElem_1_reg_285;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_194;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_262;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_190;
    end
end

always @ (*) begin
    if (((ap_predicate_op53_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op53_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op463_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op463_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_346_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else if (((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_2834_pp0_iter0_reg == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_2273_p2 = (zext_ln840_8_fu_2270_p1 + add_ln840_8_fu_2264_p2);

assign add_ln840_11_fu_881_p2 = (zext_ln1019_3_fu_823_p1 + zext_ln1019_fu_775_p1);

assign add_ln840_12_fu_887_p2 = (zext_ln1019_1_fu_791_p1 + zext_ln840_7_fu_871_p1);

assign add_ln840_13_fu_893_p2 = (add_ln840_12_fu_887_p2 + zext_ln1019_2_fu_807_p1);

assign add_ln840_14_fu_2285_p2 = (zext_ln840_10_fu_2282_p1 + zext_ln840_9_fu_2279_p1);

assign add_ln840_15_fu_2295_p2 = (zext_ln840_11_fu_2291_p1 + add_ln840_10_fu_2273_p2);

assign add_ln840_16_fu_2323_p2 = (select_ln272_5_fu_2162_p3 + zext_ln840_12_fu_2319_p1);

assign add_ln840_17_fu_1067_p2 = (zext_ln1019_11_fu_1047_p1 + zext_ln1019_10_fu_1031_p1);

assign add_ln840_18_fu_2332_p2 = (zext_ln840_14_fu_2329_p1 + add_ln840_16_fu_2323_p2);

assign add_ln840_19_fu_1073_p2 = (zext_ln1019_9_fu_1015_p1 + zext_ln1019_6_fu_967_p1);

assign add_ln840_1_fu_683_p2 = (zext_ln780_5_fu_655_p1 + zext_ln780_4_fu_623_p1);

assign add_ln840_20_fu_1079_p2 = (zext_ln1019_7_fu_983_p1 + zext_ln840_13_fu_1063_p1);

assign add_ln840_21_fu_1085_p2 = (add_ln840_20_fu_1079_p2 + zext_ln1019_8_fu_999_p1);

assign add_ln840_22_fu_2344_p2 = (zext_ln840_16_fu_2341_p1 + zext_ln840_15_fu_2338_p1);

assign add_ln840_23_fu_2354_p2 = (zext_ln840_17_fu_2350_p1 + add_ln840_18_fu_2332_p2);

assign add_ln840_24_fu_2382_p2 = (select_ln272_4_fu_2155_p3 + zext_ln840_18_fu_2378_p1);

assign add_ln840_25_fu_1259_p2 = (zext_ln1019_17_fu_1239_p1 + zext_ln1019_16_fu_1223_p1);

assign add_ln840_26_fu_2391_p2 = (zext_ln840_20_fu_2388_p1 + add_ln840_24_fu_2382_p2);

assign add_ln840_27_fu_1265_p2 = (zext_ln1019_15_fu_1207_p1 + zext_ln1019_12_fu_1159_p1);

assign add_ln840_28_fu_1271_p2 = (zext_ln1019_13_fu_1175_p1 + zext_ln840_19_fu_1255_p1);

assign add_ln840_29_fu_1277_p2 = (add_ln840_28_fu_1271_p2 + zext_ln1019_14_fu_1191_p1);

assign add_ln840_2_fu_2214_p2 = (zext_ln840_2_fu_2211_p1 + add_ln840_fu_2205_p2);

assign add_ln840_30_fu_2403_p2 = (zext_ln840_22_fu_2400_p1 + zext_ln840_21_fu_2397_p1);

assign add_ln840_31_fu_2413_p2 = (zext_ln840_23_fu_2409_p1 + add_ln840_26_fu_2391_p2);

assign add_ln840_32_fu_2441_p2 = (select_ln272_3_fu_2148_p3 + zext_ln840_24_fu_2437_p1);

assign add_ln840_33_fu_1451_p2 = (zext_ln1019_23_fu_1431_p1 + zext_ln1019_22_fu_1415_p1);

assign add_ln840_34_fu_2450_p2 = (zext_ln840_26_fu_2447_p1 + add_ln840_32_fu_2441_p2);

assign add_ln840_35_fu_1457_p2 = (zext_ln1019_21_fu_1399_p1 + zext_ln1019_18_fu_1351_p1);

assign add_ln840_36_fu_1463_p2 = (zext_ln1019_19_fu_1367_p1 + zext_ln840_25_fu_1447_p1);

assign add_ln840_37_fu_1469_p2 = (add_ln840_36_fu_1463_p2 + zext_ln1019_20_fu_1383_p1);

assign add_ln840_38_fu_2462_p2 = (zext_ln840_28_fu_2459_p1 + zext_ln840_27_fu_2456_p1);

assign add_ln840_39_fu_2472_p2 = (zext_ln840_29_fu_2468_p1 + add_ln840_34_fu_2450_p2);

assign add_ln840_3_fu_689_p2 = (zext_ln780_3_fu_599_p1 + zext_ln780_fu_527_p1);

assign add_ln840_40_fu_2500_p2 = (select_ln272_2_fu_2141_p3 + zext_ln840_30_fu_2496_p1);

assign add_ln840_41_fu_1643_p2 = (zext_ln1019_29_fu_1623_p1 + zext_ln1019_28_fu_1607_p1);

assign add_ln840_42_fu_2509_p2 = (zext_ln840_32_fu_2506_p1 + add_ln840_40_fu_2500_p2);

assign add_ln840_43_fu_1649_p2 = (zext_ln1019_27_fu_1591_p1 + zext_ln1019_24_fu_1543_p1);

assign add_ln840_44_fu_1655_p2 = (zext_ln1019_25_fu_1559_p1 + zext_ln840_31_fu_1639_p1);

assign add_ln840_45_fu_1661_p2 = (add_ln840_44_fu_1655_p2 + zext_ln1019_26_fu_1575_p1);

assign add_ln840_46_fu_2521_p2 = (zext_ln840_34_fu_2518_p1 + zext_ln840_33_fu_2515_p1);

assign add_ln840_47_fu_2531_p2 = (zext_ln840_35_fu_2527_p1 + add_ln840_42_fu_2509_p2);

assign add_ln840_48_fu_2559_p2 = (select_ln272_1_fu_2134_p3 + zext_ln840_36_fu_2555_p1);

assign add_ln840_49_fu_1835_p2 = (zext_ln1019_35_fu_1815_p1 + zext_ln1019_34_fu_1799_p1);

assign add_ln840_4_fu_695_p2 = (zext_ln780_1_fu_551_p1 + zext_ln840_1_fu_679_p1);

assign add_ln840_50_fu_2568_p2 = (zext_ln840_38_fu_2565_p1 + add_ln840_48_fu_2559_p2);

assign add_ln840_51_fu_1841_p2 = (zext_ln1019_33_fu_1783_p1 + zext_ln1019_30_fu_1735_p1);

assign add_ln840_52_fu_1847_p2 = (zext_ln1019_31_fu_1751_p1 + zext_ln840_37_fu_1831_p1);

assign add_ln840_53_fu_1853_p2 = (add_ln840_52_fu_1847_p2 + zext_ln1019_32_fu_1767_p1);

assign add_ln840_54_fu_2580_p2 = (zext_ln840_40_fu_2577_p1 + zext_ln840_39_fu_2574_p1);

assign add_ln840_55_fu_2590_p2 = (zext_ln840_41_fu_2586_p1 + add_ln840_50_fu_2568_p2);

assign add_ln840_56_fu_2618_p2 = (select_ln272_fu_2127_p3 + zext_ln840_42_fu_2614_p1);

assign add_ln840_57_fu_2027_p2 = (zext_ln1019_41_fu_2007_p1 + zext_ln1019_40_fu_1991_p1);

assign add_ln840_58_fu_2627_p2 = (zext_ln840_44_fu_2624_p1 + add_ln840_56_fu_2618_p2);

assign add_ln840_59_fu_2033_p2 = (zext_ln1019_39_fu_1975_p1 + zext_ln1019_36_fu_1927_p1);

assign add_ln840_5_fu_701_p2 = (add_ln840_4_fu_695_p2 + zext_ln780_2_fu_575_p1);

assign add_ln840_60_fu_2039_p2 = (zext_ln1019_37_fu_1943_p1 + zext_ln840_43_fu_2023_p1);

assign add_ln840_61_fu_2045_p2 = (add_ln840_60_fu_2039_p2 + zext_ln1019_38_fu_1959_p1);

assign add_ln840_62_fu_2639_p2 = (zext_ln840_46_fu_2636_p1 + zext_ln840_45_fu_2633_p1);

assign add_ln840_63_fu_2649_p2 = (zext_ln840_47_fu_2645_p1 + add_ln840_58_fu_2627_p2);

assign add_ln840_6_fu_2226_p2 = (zext_ln840_4_fu_2223_p1 + zext_ln840_3_fu_2220_p1);

assign add_ln840_7_fu_2236_p2 = (zext_ln840_5_fu_2232_p1 + add_ln840_2_fu_2214_p2);

assign add_ln840_8_fu_2264_p2 = (select_ln272_6_fu_2169_p3 + zext_ln840_6_fu_2260_p1);

assign add_ln840_9_fu_875_p2 = (zext_ln1019_5_fu_855_p1 + zext_ln1019_4_fu_839_p1);

assign add_ln840_fu_2205_p2 = (select_ln272_7_fu_2176_p3 + zext_ln840_fu_2201_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1923 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op463_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_346_p2 == 1'd0)) | ((ap_predicate_op53_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_285 = 'bx;

always @ (*) begin
    ap_predicate_op463_write_state2 = ((icmp_ln290_reg_3002 == 1'd1) & (icmp_ln249_reg_2834 == 1'd0));
end

always @ (*) begin
    ap_predicate_op53_read_state1 = ((icmp_ln253_fu_352_p2 == 1'd1) & (icmp_ln249_fu_346_p2 == 1'd0));
end

assign i_2_fu_340_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln249_fu_346_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_2834_pp0_iter0_reg = icmp_ln249_reg_2834;

assign icmp_ln253_fu_352_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_457_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_2057_p2 = ((sf_2_fu_2051_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_2074_p2 = ((nf_4_fu_2068_p2 == 32'd8) ? 1'b1 : 1'b0);

assign local_temp_V_10_fu_723_p3 = weights_V_TDATA[32'd10];

assign local_temp_V_11_fu_731_p3 = weights_V_TDATA[32'd11];

assign local_temp_V_12_fu_739_p3 = weights_V_TDATA[32'd12];

assign local_temp_V_13_fu_2242_p3 = W_packed_V_reg_2846[32'd13];

assign local_temp_V_14_fu_747_p3 = weights_V_TDATA[32'd14];

assign local_temp_V_15_fu_755_p3 = weights_V_TDATA[32'd15];

assign local_temp_V_16_fu_899_p3 = weights_V_TDATA[32'd16];

assign local_temp_V_17_fu_907_p3 = weights_V_TDATA[32'd17];

assign local_temp_V_18_fu_915_p3 = weights_V_TDATA[32'd18];

assign local_temp_V_19_fu_923_p3 = weights_V_TDATA[32'd19];

assign local_temp_V_1_fu_467_p3 = weights_V_TDATA[32'd1];

assign local_temp_V_20_fu_931_p3 = weights_V_TDATA[32'd20];

assign local_temp_V_21_fu_2301_p3 = W_packed_V_reg_2846[32'd21];

assign local_temp_V_22_fu_939_p3 = weights_V_TDATA[32'd22];

assign local_temp_V_23_fu_947_p3 = weights_V_TDATA[32'd23];

assign local_temp_V_24_fu_1091_p3 = weights_V_TDATA[32'd24];

assign local_temp_V_25_fu_1099_p3 = weights_V_TDATA[32'd25];

assign local_temp_V_26_fu_1107_p3 = weights_V_TDATA[32'd26];

assign local_temp_V_27_fu_1115_p3 = weights_V_TDATA[32'd27];

assign local_temp_V_28_fu_1123_p3 = weights_V_TDATA[32'd28];

assign local_temp_V_29_fu_2360_p3 = W_packed_V_reg_2846[32'd29];

assign local_temp_V_2_fu_475_p3 = weights_V_TDATA[32'd2];

assign local_temp_V_30_fu_1131_p3 = weights_V_TDATA[32'd30];

assign local_temp_V_31_fu_1139_p3 = weights_V_TDATA[32'd31];

assign local_temp_V_32_fu_1283_p3 = weights_V_TDATA[32'd32];

assign local_temp_V_33_fu_1291_p3 = weights_V_TDATA[32'd33];

assign local_temp_V_34_fu_1299_p3 = weights_V_TDATA[32'd34];

assign local_temp_V_35_fu_1307_p3 = weights_V_TDATA[32'd35];

assign local_temp_V_36_fu_1315_p3 = weights_V_TDATA[32'd36];

assign local_temp_V_37_fu_2419_p3 = W_packed_V_reg_2846[32'd37];

assign local_temp_V_38_fu_1323_p3 = weights_V_TDATA[32'd38];

assign local_temp_V_39_fu_1331_p3 = weights_V_TDATA[32'd39];

assign local_temp_V_3_fu_483_p3 = weights_V_TDATA[32'd3];

assign local_temp_V_40_fu_1475_p3 = weights_V_TDATA[32'd40];

assign local_temp_V_41_fu_1483_p3 = weights_V_TDATA[32'd41];

assign local_temp_V_42_fu_1491_p3 = weights_V_TDATA[32'd42];

assign local_temp_V_43_fu_1499_p3 = weights_V_TDATA[32'd43];

assign local_temp_V_44_fu_1507_p3 = weights_V_TDATA[32'd44];

assign local_temp_V_45_fu_2478_p3 = W_packed_V_reg_2846[32'd45];

assign local_temp_V_46_fu_1515_p3 = weights_V_TDATA[32'd46];

assign local_temp_V_47_fu_1523_p3 = weights_V_TDATA[32'd47];

assign local_temp_V_48_fu_1667_p3 = weights_V_TDATA[32'd48];

assign local_temp_V_49_fu_1675_p3 = weights_V_TDATA[32'd49];

assign local_temp_V_4_fu_491_p3 = weights_V_TDATA[32'd4];

assign local_temp_V_50_fu_1683_p3 = weights_V_TDATA[32'd50];

assign local_temp_V_51_fu_1691_p3 = weights_V_TDATA[32'd51];

assign local_temp_V_52_fu_1699_p3 = weights_V_TDATA[32'd52];

assign local_temp_V_53_fu_2537_p3 = W_packed_V_reg_2846[32'd53];

assign local_temp_V_54_fu_1707_p3 = weights_V_TDATA[32'd54];

assign local_temp_V_55_fu_1715_p3 = weights_V_TDATA[32'd55];

assign local_temp_V_56_fu_1859_p3 = weights_V_TDATA[32'd56];

assign local_temp_V_57_fu_1867_p3 = weights_V_TDATA[32'd57];

assign local_temp_V_58_fu_1875_p3 = weights_V_TDATA[32'd58];

assign local_temp_V_59_fu_1883_p3 = weights_V_TDATA[32'd59];

assign local_temp_V_5_fu_2183_p3 = W_packed_V_reg_2846[32'd5];

assign local_temp_V_60_fu_1891_p3 = weights_V_TDATA[32'd60];

assign local_temp_V_61_fu_2596_p3 = W_packed_V_reg_2846[32'd61];

assign local_temp_V_62_fu_1899_p3 = weights_V_TDATA[32'd62];

assign local_temp_V_63_fu_1907_p3 = weights_V_TDATA[32'd63];

assign local_temp_V_6_fu_499_p3 = weights_V_TDATA[32'd6];

assign local_temp_V_7_fu_507_p3 = weights_V_TDATA[32'd7];

assign local_temp_V_8_fu_707_p3 = weights_V_TDATA[32'd8];

assign local_temp_V_9_fu_715_p3 = weights_V_TDATA[32'd9];

assign local_temp_V_fu_463_p1 = weights_V_TDATA[0:0];

assign nf_4_fu_2068_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_2080_p3 = ((icmp_ln302_fu_2074_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_2068_p2);

assign out_V_TDATA = {{{{{{{{add_ln840_63_fu_2649_p2}, {add_ln840_55_fu_2590_p2}}, {add_ln840_47_fu_2531_p2}}, {add_ln840_39_fu_2472_p2}}, {add_ln840_31_fu_2413_p2}}, {add_ln840_23_fu_2354_p2}}, {add_ln840_15_fu_2295_p2}}, {add_ln840_7_fu_2236_p2}};

assign p_Result_1_fu_531_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd1];

assign p_Result_2_fu_555_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd2];

assign p_Result_3_fu_579_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd3];

assign p_Result_4_fu_603_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd4];

assign p_Result_6_fu_635_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd6];

assign p_Result_7_fu_659_p3 = ap_phi_mux_inElem_1_phi_fu_288_p18[32'd7];

assign p_Result_s_fu_453_p1 = ap_phi_mux_inElem_1_phi_fu_288_p18[0:0];

assign select_ln272_1_fu_2134_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_6_7150_fu_222);

assign select_ln272_2_fu_2141_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_5_7148_fu_218);

assign select_ln272_3_fu_2148_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_4_7146_fu_214);

assign select_ln272_4_fu_2155_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_3_7144_fu_210);

assign select_ln272_5_fu_2162_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_2_7142_fu_206);

assign select_ln272_6_fu_2169_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_1_7140_fu_202);

assign select_ln272_7_fu_2176_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_776138_fu_198);

assign select_ln272_fu_2127_p3 = ((icmp_ln272_reg_2858[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_7_7152_fu_226);

assign sf_2_fu_2051_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_386_p9 = ap_sig_allocacmp_sf_1[2:0];

assign trunc_ln257_fu_409_p1 = ap_sig_allocacmp_sf_1[2:0];

assign xor_ln1019_100_fu_1755_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_50_fu_1683_p3);

assign xor_ln1019_101_fu_1761_p2 = (xor_ln1019_100_fu_1755_p2 ^ 1'd1);

assign xor_ln1019_102_fu_1771_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_51_fu_1691_p3);

assign xor_ln1019_103_fu_1777_p2 = (xor_ln1019_102_fu_1771_p2 ^ 1'd1);

assign xor_ln1019_104_fu_1787_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_52_fu_1699_p3);

assign xor_ln1019_105_fu_1793_p2 = (xor_ln1019_104_fu_1787_p2 ^ 1'd1);

assign xor_ln1019_106_fu_2544_p2 = (p_Result_5_reg_2870 ^ local_temp_V_53_fu_2537_p3);

assign xor_ln1019_107_fu_2549_p2 = (xor_ln1019_106_fu_2544_p2 ^ 1'd1);

assign xor_ln1019_108_fu_1803_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_54_fu_1707_p3);

assign xor_ln1019_109_fu_1809_p2 = (xor_ln1019_108_fu_1803_p2 ^ 1'd1);

assign xor_ln1019_10_fu_2190_p2 = (p_Result_5_reg_2870 ^ local_temp_V_5_fu_2183_p3);

assign xor_ln1019_110_fu_1819_p2 = (local_temp_V_55_fu_1715_p3 ^ 1'd1);

assign xor_ln1019_111_fu_1825_p2 = (xor_ln1019_110_fu_1819_p2 ^ p_Result_7_fu_659_p3);

assign xor_ln1019_112_fu_1915_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_56_fu_1859_p3);

assign xor_ln1019_113_fu_1921_p2 = (xor_ln1019_112_fu_1915_p2 ^ 1'd1);

assign xor_ln1019_114_fu_1931_p2 = (local_temp_V_57_fu_1867_p3 ^ 1'd1);

assign xor_ln1019_115_fu_1937_p2 = (xor_ln1019_114_fu_1931_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_116_fu_1947_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_58_fu_1875_p3);

assign xor_ln1019_117_fu_1953_p2 = (xor_ln1019_116_fu_1947_p2 ^ 1'd1);

assign xor_ln1019_118_fu_1963_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_59_fu_1883_p3);

assign xor_ln1019_119_fu_1969_p2 = (xor_ln1019_118_fu_1963_p2 ^ 1'd1);

assign xor_ln1019_11_fu_2195_p2 = (xor_ln1019_10_fu_2190_p2 ^ 1'd1);

assign xor_ln1019_120_fu_1979_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_60_fu_1891_p3);

assign xor_ln1019_121_fu_1985_p2 = (xor_ln1019_120_fu_1979_p2 ^ 1'd1);

assign xor_ln1019_122_fu_2603_p2 = (p_Result_5_reg_2870 ^ local_temp_V_61_fu_2596_p3);

assign xor_ln1019_123_fu_2608_p2 = (xor_ln1019_122_fu_2603_p2 ^ 1'd1);

assign xor_ln1019_124_fu_1995_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_62_fu_1899_p3);

assign xor_ln1019_125_fu_2001_p2 = (xor_ln1019_124_fu_1995_p2 ^ 1'd1);

assign xor_ln1019_126_fu_2011_p2 = (local_temp_V_63_fu_1907_p3 ^ 1'd1);

assign xor_ln1019_127_fu_2017_p2 = (xor_ln1019_126_fu_2011_p2 ^ p_Result_7_fu_659_p3);

assign xor_ln1019_12_fu_643_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_6_fu_499_p3);

assign xor_ln1019_13_fu_649_p2 = (xor_ln1019_12_fu_643_p2 ^ 1'd1);

assign xor_ln1019_14_fu_667_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_7_fu_507_p3);

assign xor_ln1019_15_fu_673_p2 = (xor_ln1019_14_fu_667_p2 ^ 1'd1);

assign xor_ln1019_16_fu_763_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_8_fu_707_p3);

assign xor_ln1019_17_fu_769_p2 = (xor_ln1019_16_fu_763_p2 ^ 1'd1);

assign xor_ln1019_18_fu_779_p2 = (local_temp_V_9_fu_715_p3 ^ 1'd1);

assign xor_ln1019_19_fu_785_p2 = (xor_ln1019_18_fu_779_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_1_fu_521_p2 = (xor_ln1019_fu_515_p2 ^ 1'd1);

assign xor_ln1019_20_fu_795_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_10_fu_723_p3);

assign xor_ln1019_21_fu_801_p2 = (xor_ln1019_20_fu_795_p2 ^ 1'd1);

assign xor_ln1019_22_fu_811_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_11_fu_731_p3);

assign xor_ln1019_23_fu_817_p2 = (xor_ln1019_22_fu_811_p2 ^ 1'd1);

assign xor_ln1019_24_fu_827_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_12_fu_739_p3);

assign xor_ln1019_25_fu_833_p2 = (xor_ln1019_24_fu_827_p2 ^ 1'd1);

assign xor_ln1019_26_fu_2249_p2 = (p_Result_5_reg_2870 ^ local_temp_V_13_fu_2242_p3);

assign xor_ln1019_27_fu_2254_p2 = (xor_ln1019_26_fu_2249_p2 ^ 1'd1);

assign xor_ln1019_28_fu_843_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_14_fu_747_p3);

assign xor_ln1019_29_fu_849_p2 = (xor_ln1019_28_fu_843_p2 ^ 1'd1);

assign xor_ln1019_2_fu_539_p2 = (local_temp_V_1_fu_467_p3 ^ 1'd1);

assign xor_ln1019_30_fu_859_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_15_fu_755_p3);

assign xor_ln1019_31_fu_865_p2 = (xor_ln1019_30_fu_859_p2 ^ 1'd1);

assign xor_ln1019_32_fu_955_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_16_fu_899_p3);

assign xor_ln1019_33_fu_961_p2 = (xor_ln1019_32_fu_955_p2 ^ 1'd1);

assign xor_ln1019_34_fu_971_p2 = (local_temp_V_17_fu_907_p3 ^ 1'd1);

assign xor_ln1019_35_fu_977_p2 = (xor_ln1019_34_fu_971_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_36_fu_987_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_18_fu_915_p3);

assign xor_ln1019_37_fu_993_p2 = (xor_ln1019_36_fu_987_p2 ^ 1'd1);

assign xor_ln1019_38_fu_1003_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_19_fu_923_p3);

assign xor_ln1019_39_fu_1009_p2 = (xor_ln1019_38_fu_1003_p2 ^ 1'd1);

assign xor_ln1019_3_fu_545_p2 = (xor_ln1019_2_fu_539_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_40_fu_1019_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_20_fu_931_p3);

assign xor_ln1019_41_fu_1025_p2 = (xor_ln1019_40_fu_1019_p2 ^ 1'd1);

assign xor_ln1019_42_fu_2308_p2 = (p_Result_5_reg_2870 ^ local_temp_V_21_fu_2301_p3);

assign xor_ln1019_43_fu_2313_p2 = (xor_ln1019_42_fu_2308_p2 ^ 1'd1);

assign xor_ln1019_44_fu_1035_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_22_fu_939_p3);

assign xor_ln1019_45_fu_1041_p2 = (xor_ln1019_44_fu_1035_p2 ^ 1'd1);

assign xor_ln1019_46_fu_1051_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_23_fu_947_p3);

assign xor_ln1019_47_fu_1057_p2 = (xor_ln1019_46_fu_1051_p2 ^ 1'd1);

assign xor_ln1019_48_fu_1147_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_24_fu_1091_p3);

assign xor_ln1019_49_fu_1153_p2 = (xor_ln1019_48_fu_1147_p2 ^ 1'd1);

assign xor_ln1019_4_fu_563_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_2_fu_475_p3);

assign xor_ln1019_50_fu_1163_p2 = (local_temp_V_25_fu_1099_p3 ^ 1'd1);

assign xor_ln1019_51_fu_1169_p2 = (xor_ln1019_50_fu_1163_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_52_fu_1179_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_26_fu_1107_p3);

assign xor_ln1019_53_fu_1185_p2 = (xor_ln1019_52_fu_1179_p2 ^ 1'd1);

assign xor_ln1019_54_fu_1195_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_27_fu_1115_p3);

assign xor_ln1019_55_fu_1201_p2 = (xor_ln1019_54_fu_1195_p2 ^ 1'd1);

assign xor_ln1019_56_fu_1211_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_28_fu_1123_p3);

assign xor_ln1019_57_fu_1217_p2 = (xor_ln1019_56_fu_1211_p2 ^ 1'd1);

assign xor_ln1019_58_fu_2367_p2 = (p_Result_5_reg_2870 ^ local_temp_V_29_fu_2360_p3);

assign xor_ln1019_59_fu_2372_p2 = (xor_ln1019_58_fu_2367_p2 ^ 1'd1);

assign xor_ln1019_5_fu_569_p2 = (xor_ln1019_4_fu_563_p2 ^ 1'd1);

assign xor_ln1019_60_fu_1227_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_30_fu_1131_p3);

assign xor_ln1019_61_fu_1233_p2 = (xor_ln1019_60_fu_1227_p2 ^ 1'd1);

assign xor_ln1019_62_fu_1243_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_31_fu_1139_p3);

assign xor_ln1019_63_fu_1249_p2 = (xor_ln1019_62_fu_1243_p2 ^ 1'd1);

assign xor_ln1019_64_fu_1339_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_32_fu_1283_p3);

assign xor_ln1019_65_fu_1345_p2 = (xor_ln1019_64_fu_1339_p2 ^ 1'd1);

assign xor_ln1019_66_fu_1355_p2 = (local_temp_V_33_fu_1291_p3 ^ 1'd1);

assign xor_ln1019_67_fu_1361_p2 = (xor_ln1019_66_fu_1355_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_68_fu_1371_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_34_fu_1299_p3);

assign xor_ln1019_69_fu_1377_p2 = (xor_ln1019_68_fu_1371_p2 ^ 1'd1);

assign xor_ln1019_6_fu_587_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_3_fu_483_p3);

assign xor_ln1019_70_fu_1387_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_35_fu_1307_p3);

assign xor_ln1019_71_fu_1393_p2 = (xor_ln1019_70_fu_1387_p2 ^ 1'd1);

assign xor_ln1019_72_fu_1403_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_36_fu_1315_p3);

assign xor_ln1019_73_fu_1409_p2 = (xor_ln1019_72_fu_1403_p2 ^ 1'd1);

assign xor_ln1019_74_fu_2426_p2 = (p_Result_5_reg_2870 ^ local_temp_V_37_fu_2419_p3);

assign xor_ln1019_75_fu_2431_p2 = (xor_ln1019_74_fu_2426_p2 ^ 1'd1);

assign xor_ln1019_76_fu_1419_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_38_fu_1323_p3);

assign xor_ln1019_77_fu_1425_p2 = (xor_ln1019_76_fu_1419_p2 ^ 1'd1);

assign xor_ln1019_78_fu_1435_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_39_fu_1331_p3);

assign xor_ln1019_79_fu_1441_p2 = (xor_ln1019_78_fu_1435_p2 ^ 1'd1);

assign xor_ln1019_7_fu_593_p2 = (xor_ln1019_6_fu_587_p2 ^ 1'd1);

assign xor_ln1019_80_fu_1531_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_40_fu_1475_p3);

assign xor_ln1019_81_fu_1537_p2 = (xor_ln1019_80_fu_1531_p2 ^ 1'd1);

assign xor_ln1019_82_fu_1547_p2 = (local_temp_V_41_fu_1483_p3 ^ 1'd1);

assign xor_ln1019_83_fu_1553_p2 = (xor_ln1019_82_fu_1547_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_84_fu_1563_p2 = (p_Result_2_fu_555_p3 ^ local_temp_V_42_fu_1491_p3);

assign xor_ln1019_85_fu_1569_p2 = (xor_ln1019_84_fu_1563_p2 ^ 1'd1);

assign xor_ln1019_86_fu_1579_p2 = (p_Result_3_fu_579_p3 ^ local_temp_V_43_fu_1499_p3);

assign xor_ln1019_87_fu_1585_p2 = (xor_ln1019_86_fu_1579_p2 ^ 1'd1);

assign xor_ln1019_88_fu_1595_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_44_fu_1507_p3);

assign xor_ln1019_89_fu_1601_p2 = (xor_ln1019_88_fu_1595_p2 ^ 1'd1);

assign xor_ln1019_8_fu_611_p2 = (p_Result_4_fu_603_p3 ^ local_temp_V_4_fu_491_p3);

assign xor_ln1019_90_fu_2485_p2 = (p_Result_5_reg_2870 ^ local_temp_V_45_fu_2478_p3);

assign xor_ln1019_91_fu_2490_p2 = (xor_ln1019_90_fu_2485_p2 ^ 1'd1);

assign xor_ln1019_92_fu_1611_p2 = (p_Result_6_fu_635_p3 ^ local_temp_V_46_fu_1515_p3);

assign xor_ln1019_93_fu_1617_p2 = (xor_ln1019_92_fu_1611_p2 ^ 1'd1);

assign xor_ln1019_94_fu_1627_p2 = (p_Result_7_fu_659_p3 ^ local_temp_V_47_fu_1523_p3);

assign xor_ln1019_95_fu_1633_p2 = (xor_ln1019_94_fu_1627_p2 ^ 1'd1);

assign xor_ln1019_96_fu_1723_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_48_fu_1667_p3);

assign xor_ln1019_97_fu_1729_p2 = (xor_ln1019_96_fu_1723_p2 ^ 1'd1);

assign xor_ln1019_98_fu_1739_p2 = (local_temp_V_49_fu_1675_p3 ^ 1'd1);

assign xor_ln1019_99_fu_1745_p2 = (xor_ln1019_98_fu_1739_p2 ^ p_Result_1_fu_531_p3);

assign xor_ln1019_9_fu_617_p2 = (xor_ln1019_8_fu_611_p2 ^ 1'd1);

assign xor_ln1019_fu_515_p2 = (p_Result_s_fu_453_p1 ^ local_temp_V_fu_463_p1);

assign zext_ln1019_10_fu_1031_p1 = xor_ln1019_41_fu_1025_p2;

assign zext_ln1019_11_fu_1047_p1 = xor_ln1019_45_fu_1041_p2;

assign zext_ln1019_12_fu_1159_p1 = xor_ln1019_49_fu_1153_p2;

assign zext_ln1019_13_fu_1175_p1 = xor_ln1019_51_fu_1169_p2;

assign zext_ln1019_14_fu_1191_p1 = xor_ln1019_53_fu_1185_p2;

assign zext_ln1019_15_fu_1207_p1 = xor_ln1019_55_fu_1201_p2;

assign zext_ln1019_16_fu_1223_p1 = xor_ln1019_57_fu_1217_p2;

assign zext_ln1019_17_fu_1239_p1 = xor_ln1019_61_fu_1233_p2;

assign zext_ln1019_18_fu_1351_p1 = xor_ln1019_65_fu_1345_p2;

assign zext_ln1019_19_fu_1367_p1 = xor_ln1019_67_fu_1361_p2;

assign zext_ln1019_1_fu_791_p1 = xor_ln1019_19_fu_785_p2;

assign zext_ln1019_20_fu_1383_p1 = xor_ln1019_69_fu_1377_p2;

assign zext_ln1019_21_fu_1399_p1 = xor_ln1019_71_fu_1393_p2;

assign zext_ln1019_22_fu_1415_p1 = xor_ln1019_73_fu_1409_p2;

assign zext_ln1019_23_fu_1431_p1 = xor_ln1019_77_fu_1425_p2;

assign zext_ln1019_24_fu_1543_p1 = xor_ln1019_81_fu_1537_p2;

assign zext_ln1019_25_fu_1559_p1 = xor_ln1019_83_fu_1553_p2;

assign zext_ln1019_26_fu_1575_p1 = xor_ln1019_85_fu_1569_p2;

assign zext_ln1019_27_fu_1591_p1 = xor_ln1019_87_fu_1585_p2;

assign zext_ln1019_28_fu_1607_p1 = xor_ln1019_89_fu_1601_p2;

assign zext_ln1019_29_fu_1623_p1 = xor_ln1019_93_fu_1617_p2;

assign zext_ln1019_2_fu_807_p1 = xor_ln1019_21_fu_801_p2;

assign zext_ln1019_30_fu_1735_p1 = xor_ln1019_97_fu_1729_p2;

assign zext_ln1019_31_fu_1751_p1 = xor_ln1019_99_fu_1745_p2;

assign zext_ln1019_32_fu_1767_p1 = xor_ln1019_101_fu_1761_p2;

assign zext_ln1019_33_fu_1783_p1 = xor_ln1019_103_fu_1777_p2;

assign zext_ln1019_34_fu_1799_p1 = xor_ln1019_105_fu_1793_p2;

assign zext_ln1019_35_fu_1815_p1 = xor_ln1019_109_fu_1809_p2;

assign zext_ln1019_36_fu_1927_p1 = xor_ln1019_113_fu_1921_p2;

assign zext_ln1019_37_fu_1943_p1 = xor_ln1019_115_fu_1937_p2;

assign zext_ln1019_38_fu_1959_p1 = xor_ln1019_117_fu_1953_p2;

assign zext_ln1019_39_fu_1975_p1 = xor_ln1019_119_fu_1969_p2;

assign zext_ln1019_3_fu_823_p1 = xor_ln1019_23_fu_817_p2;

assign zext_ln1019_40_fu_1991_p1 = xor_ln1019_121_fu_1985_p2;

assign zext_ln1019_41_fu_2007_p1 = xor_ln1019_125_fu_2001_p2;

assign zext_ln1019_4_fu_839_p1 = xor_ln1019_25_fu_833_p2;

assign zext_ln1019_5_fu_855_p1 = xor_ln1019_29_fu_849_p2;

assign zext_ln1019_6_fu_967_p1 = xor_ln1019_33_fu_961_p2;

assign zext_ln1019_7_fu_983_p1 = xor_ln1019_35_fu_977_p2;

assign zext_ln1019_8_fu_999_p1 = xor_ln1019_37_fu_993_p2;

assign zext_ln1019_9_fu_1015_p1 = xor_ln1019_39_fu_1009_p2;

assign zext_ln1019_fu_775_p1 = xor_ln1019_17_fu_769_p2;

assign zext_ln780_1_fu_551_p1 = xor_ln1019_3_fu_545_p2;

assign zext_ln780_2_fu_575_p1 = xor_ln1019_5_fu_569_p2;

assign zext_ln780_3_fu_599_p1 = xor_ln1019_7_fu_593_p2;

assign zext_ln780_4_fu_623_p1 = xor_ln1019_9_fu_617_p2;

assign zext_ln780_5_fu_655_p1 = xor_ln1019_13_fu_649_p2;

assign zext_ln780_fu_527_p1 = xor_ln1019_1_fu_521_p2;

assign zext_ln840_10_fu_2282_p1 = add_ln840_13_reg_2907;

assign zext_ln840_11_fu_2291_p1 = add_ln840_14_fu_2285_p2;

assign zext_ln840_12_fu_2319_p1 = xor_ln1019_43_fu_2313_p2;

assign zext_ln840_13_fu_1063_p1 = xor_ln1019_47_fu_1057_p2;

assign zext_ln840_14_fu_2329_p1 = add_ln840_17_reg_2912;

assign zext_ln840_15_fu_2338_p1 = add_ln840_19_reg_2917;

assign zext_ln840_16_fu_2341_p1 = add_ln840_21_reg_2922;

assign zext_ln840_17_fu_2350_p1 = add_ln840_22_fu_2344_p2;

assign zext_ln840_18_fu_2378_p1 = xor_ln1019_59_fu_2372_p2;

assign zext_ln840_19_fu_1255_p1 = xor_ln1019_63_fu_1249_p2;

assign zext_ln840_1_fu_679_p1 = xor_ln1019_15_fu_673_p2;

assign zext_ln840_20_fu_2388_p1 = add_ln840_25_reg_2927;

assign zext_ln840_21_fu_2397_p1 = add_ln840_27_reg_2932;

assign zext_ln840_22_fu_2400_p1 = add_ln840_29_reg_2937;

assign zext_ln840_23_fu_2409_p1 = add_ln840_30_fu_2403_p2;

assign zext_ln840_24_fu_2437_p1 = xor_ln1019_75_fu_2431_p2;

assign zext_ln840_25_fu_1447_p1 = xor_ln1019_79_fu_1441_p2;

assign zext_ln840_26_fu_2447_p1 = add_ln840_33_reg_2942;

assign zext_ln840_27_fu_2456_p1 = add_ln840_35_reg_2947;

assign zext_ln840_28_fu_2459_p1 = add_ln840_37_reg_2952;

assign zext_ln840_29_fu_2468_p1 = add_ln840_38_fu_2462_p2;

assign zext_ln840_2_fu_2211_p1 = add_ln840_1_reg_2882;

assign zext_ln840_30_fu_2496_p1 = xor_ln1019_91_fu_2490_p2;

assign zext_ln840_31_fu_1639_p1 = xor_ln1019_95_fu_1633_p2;

assign zext_ln840_32_fu_2506_p1 = add_ln840_41_reg_2957;

assign zext_ln840_33_fu_2515_p1 = add_ln840_43_reg_2962;

assign zext_ln840_34_fu_2518_p1 = add_ln840_45_reg_2967;

assign zext_ln840_35_fu_2527_p1 = add_ln840_46_fu_2521_p2;

assign zext_ln840_36_fu_2555_p1 = xor_ln1019_107_fu_2549_p2;

assign zext_ln840_37_fu_1831_p1 = xor_ln1019_111_fu_1825_p2;

assign zext_ln840_38_fu_2565_p1 = add_ln840_49_reg_2972;

assign zext_ln840_39_fu_2574_p1 = add_ln840_51_reg_2977;

assign zext_ln840_3_fu_2220_p1 = add_ln840_3_reg_2887;

assign zext_ln840_40_fu_2577_p1 = add_ln840_53_reg_2982;

assign zext_ln840_41_fu_2586_p1 = add_ln840_54_fu_2580_p2;

assign zext_ln840_42_fu_2614_p1 = xor_ln1019_123_fu_2608_p2;

assign zext_ln840_43_fu_2023_p1 = xor_ln1019_127_fu_2017_p2;

assign zext_ln840_44_fu_2624_p1 = add_ln840_57_reg_2987;

assign zext_ln840_45_fu_2633_p1 = add_ln840_59_reg_2992;

assign zext_ln840_46_fu_2636_p1 = add_ln840_61_reg_2997;

assign zext_ln840_47_fu_2645_p1 = add_ln840_62_fu_2639_p2;

assign zext_ln840_4_fu_2223_p1 = add_ln840_5_reg_2892;

assign zext_ln840_5_fu_2232_p1 = add_ln840_6_fu_2226_p2;

assign zext_ln840_6_fu_2260_p1 = xor_ln1019_27_fu_2254_p2;

assign zext_ln840_7_fu_871_p1 = xor_ln1019_31_fu_865_p2;

assign zext_ln840_8_fu_2270_p1 = add_ln840_9_reg_2897;

assign zext_ln840_9_fu_2279_p1 = add_ln840_11_reg_2902;

assign zext_ln840_fu_2201_p1 = xor_ln1019_11_fu_2195_p2;

endmodule //MatrixVectorActivation_1_Matrix_Vector_Activate_Stream_Batch
