// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MatrixVectorActivation_3_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [71:0] out_V_TDATA;
output   out_V_TVALID;
input  [79:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] icmp_ln249_fu_294_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln249_reg_3186;
wire   [0:0] icmp_ln249_reg_3186_pp0_iter0_reg;
reg   [0:0] icmp_ln290_reg_3304;
reg    ap_predicate_op511_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
wire   [0:0] icmp_ln272_fu_307_p2;
reg   [0:0] icmp_ln272_reg_3190;
wire   [6:0] add_ln840_fu_567_p2;
reg   [6:0] add_ln840_reg_3204;
wire   [2:0] add_ln840_6_fu_599_p2;
reg   [2:0] add_ln840_6_reg_3209;
wire   [6:0] add_ln840_8_fu_807_p2;
reg   [6:0] add_ln840_8_reg_3214;
wire   [2:0] add_ln840_14_fu_839_p2;
reg   [2:0] add_ln840_14_reg_3219;
wire   [6:0] add_ln840_16_fu_1047_p2;
reg   [6:0] add_ln840_16_reg_3224;
wire   [2:0] add_ln840_22_fu_1079_p2;
reg   [2:0] add_ln840_22_reg_3229;
wire   [6:0] add_ln840_24_fu_1287_p2;
reg   [6:0] add_ln840_24_reg_3234;
wire   [2:0] add_ln840_30_fu_1319_p2;
reg   [2:0] add_ln840_30_reg_3239;
wire   [6:0] add_ln840_32_fu_1527_p2;
reg   [6:0] add_ln840_32_reg_3244;
wire   [2:0] add_ln840_38_fu_1559_p2;
reg   [2:0] add_ln840_38_reg_3249;
wire   [6:0] add_ln840_40_fu_1767_p2;
reg   [6:0] add_ln840_40_reg_3254;
wire   [2:0] add_ln840_46_fu_1799_p2;
reg   [2:0] add_ln840_46_reg_3259;
wire   [6:0] add_ln840_48_fu_2007_p2;
reg   [6:0] add_ln840_48_reg_3264;
wire   [2:0] add_ln840_54_fu_2039_p2;
reg   [2:0] add_ln840_54_reg_3269;
wire   [6:0] add_ln840_56_fu_2247_p2;
reg   [6:0] add_ln840_56_reg_3274;
wire   [2:0] add_ln840_62_fu_2279_p2;
reg   [2:0] add_ln840_62_reg_3279;
wire   [6:0] add_ln840_64_fu_2487_p2;
reg   [6:0] add_ln840_64_reg_3284;
wire   [2:0] add_ln840_70_fu_2519_p2;
reg   [2:0] add_ln840_70_reg_3289;
wire   [6:0] add_ln840_72_fu_2727_p2;
reg   [6:0] add_ln840_72_reg_3294;
wire   [2:0] add_ln840_78_fu_2759_p2;
reg   [2:0] add_ln840_78_reg_3299;
wire   [0:0] icmp_ln290_fu_2771_p2;
reg   [31:0] sf_fu_208;
wire   [31:0] sf_1_fu_2765_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_load;
reg   [3:0] i_fu_212;
wire   [3:0] i_2_fu_288_p2;
reg   [3:0] ap_sig_allocacmp_i_1;
reg   [6:0] add_i_i_i2_775138_fu_216;
wire   [6:0] add_ln840_7_fu_2900_p2;
reg   [6:0] add_i_i_i2_1_7140_fu_220;
wire   [6:0] add_ln840_15_fu_2914_p2;
reg   [6:0] add_i_i_i2_2_7142_fu_224;
wire   [6:0] add_ln840_23_fu_2928_p2;
reg   [6:0] add_i_i_i2_3_7144_fu_228;
wire   [6:0] add_ln840_31_fu_2942_p2;
reg   [6:0] add_i_i_i2_4_7146_fu_232;
wire   [6:0] add_ln840_39_fu_2956_p2;
reg   [6:0] add_i_i_i2_5_7148_fu_236;
wire   [6:0] add_ln840_47_fu_2970_p2;
reg   [6:0] add_i_i_i2_6_7150_fu_240;
wire   [6:0] add_ln840_55_fu_2984_p2;
reg   [6:0] add_i_i_i2_7_7152_fu_244;
wire   [6:0] add_ln840_63_fu_2998_p2;
reg   [6:0] add_i_i_i2_8_7154_fu_248;
wire   [6:0] add_ln840_71_fu_3012_p2;
reg   [6:0] add_i_i_i2_9_7156_fu_252;
wire   [6:0] add_ln840_79_fu_3026_p2;
wire   [0:0] p_Result_s_fu_303_p1;
wire   [0:0] local_temp_V_fu_313_p1;
wire   [0:0] xor_ln1019_fu_373_p2;
wire   [0:0] xor_ln1019_1_fu_379_p2;
wire   [0:0] p_Result_1_fu_389_p3;
wire   [0:0] local_temp_V_1_fu_317_p3;
wire   [0:0] xor_ln1019_2_fu_397_p2;
wire   [0:0] xor_ln1019_3_fu_403_p2;
wire   [0:0] p_Result_2_fu_413_p3;
wire   [0:0] local_temp_V_2_fu_325_p3;
wire   [0:0] xor_ln1019_4_fu_421_p2;
wire   [0:0] xor_ln1019_5_fu_427_p2;
wire   [0:0] p_Result_3_fu_437_p3;
wire   [0:0] local_temp_V_3_fu_333_p3;
wire   [0:0] xor_ln1019_6_fu_445_p2;
wire   [0:0] xor_ln1019_7_fu_451_p2;
wire   [0:0] p_Result_4_fu_461_p3;
wire   [0:0] local_temp_V_4_fu_341_p3;
wire   [0:0] xor_ln1019_8_fu_469_p2;
wire   [0:0] xor_ln1019_9_fu_475_p2;
wire   [0:0] p_Result_5_fu_485_p3;
wire   [0:0] local_temp_V_5_fu_349_p3;
wire   [0:0] xor_ln1019_10_fu_493_p2;
wire   [0:0] xor_ln1019_11_fu_499_p2;
wire   [0:0] p_Result_6_fu_509_p3;
wire   [0:0] local_temp_V_6_fu_357_p3;
wire   [0:0] xor_ln1019_12_fu_517_p2;
wire   [0:0] xor_ln1019_13_fu_523_p2;
wire   [0:0] p_Result_7_fu_533_p3;
wire   [0:0] local_temp_V_7_fu_365_p3;
wire   [0:0] xor_ln1019_14_fu_541_p2;
wire   [0:0] xor_ln1019_15_fu_547_p2;
wire   [1:0] zext_ln780_5_fu_529_p1;
wire   [1:0] zext_ln780_4_fu_481_p1;
wire   [1:0] add_ln840_1_fu_557_p2;
wire   [6:0] zext_ln840_2_fu_563_p1;
wire   [6:0] zext_ln840_fu_505_p1;
wire   [1:0] zext_ln780_3_fu_457_p1;
wire   [1:0] zext_ln780_fu_385_p1;
wire   [1:0] add_ln840_3_fu_573_p2;
wire   [1:0] zext_ln780_1_fu_409_p1;
wire   [1:0] zext_ln840_1_fu_553_p1;
wire   [1:0] add_ln840_4_fu_583_p2;
wire   [1:0] zext_ln780_2_fu_433_p1;
wire   [1:0] add_ln840_5_fu_589_p2;
wire   [2:0] zext_ln840_4_fu_595_p1;
wire   [2:0] zext_ln840_3_fu_579_p1;
wire   [0:0] local_temp_V_8_fu_605_p3;
wire   [0:0] xor_ln1019_16_fu_669_p2;
wire   [0:0] xor_ln1019_17_fu_675_p2;
wire   [0:0] local_temp_V_9_fu_613_p3;
wire   [0:0] xor_ln1019_18_fu_685_p2;
wire   [0:0] xor_ln1019_19_fu_691_p2;
wire   [0:0] local_temp_V_10_fu_621_p3;
wire   [0:0] xor_ln1019_20_fu_701_p2;
wire   [0:0] xor_ln1019_21_fu_707_p2;
wire   [0:0] local_temp_V_11_fu_629_p3;
wire   [0:0] xor_ln1019_22_fu_717_p2;
wire   [0:0] xor_ln1019_23_fu_723_p2;
wire   [0:0] local_temp_V_12_fu_637_p3;
wire   [0:0] xor_ln1019_24_fu_733_p2;
wire   [0:0] xor_ln1019_25_fu_739_p2;
wire   [0:0] local_temp_V_13_fu_645_p3;
wire   [0:0] xor_ln1019_26_fu_749_p2;
wire   [0:0] xor_ln1019_27_fu_755_p2;
wire   [0:0] local_temp_V_14_fu_653_p3;
wire   [0:0] xor_ln1019_28_fu_765_p2;
wire   [0:0] xor_ln1019_29_fu_771_p2;
wire   [0:0] local_temp_V_15_fu_661_p3;
wire   [0:0] xor_ln1019_30_fu_781_p2;
wire   [0:0] xor_ln1019_31_fu_787_p2;
wire   [1:0] zext_ln1019_5_fu_777_p1;
wire   [1:0] zext_ln1019_4_fu_745_p1;
wire   [1:0] add_ln840_9_fu_797_p2;
wire   [6:0] zext_ln840_8_fu_803_p1;
wire   [6:0] zext_ln840_6_fu_761_p1;
wire   [1:0] zext_ln1019_3_fu_729_p1;
wire   [1:0] zext_ln1019_fu_681_p1;
wire   [1:0] add_ln840_11_fu_813_p2;
wire   [1:0] zext_ln1019_1_fu_697_p1;
wire   [1:0] zext_ln840_7_fu_793_p1;
wire   [1:0] add_ln840_12_fu_823_p2;
wire   [1:0] zext_ln1019_2_fu_713_p1;
wire   [1:0] add_ln840_13_fu_829_p2;
wire   [2:0] zext_ln840_10_fu_835_p1;
wire   [2:0] zext_ln840_9_fu_819_p1;
wire   [0:0] local_temp_V_16_fu_845_p3;
wire   [0:0] xor_ln1019_32_fu_909_p2;
wire   [0:0] xor_ln1019_33_fu_915_p2;
wire   [0:0] local_temp_V_17_fu_853_p3;
wire   [0:0] xor_ln1019_34_fu_925_p2;
wire   [0:0] xor_ln1019_35_fu_931_p2;
wire   [0:0] local_temp_V_18_fu_861_p3;
wire   [0:0] xor_ln1019_36_fu_941_p2;
wire   [0:0] xor_ln1019_37_fu_947_p2;
wire   [0:0] local_temp_V_19_fu_869_p3;
wire   [0:0] xor_ln1019_38_fu_957_p2;
wire   [0:0] xor_ln1019_39_fu_963_p2;
wire   [0:0] local_temp_V_20_fu_877_p3;
wire   [0:0] xor_ln1019_40_fu_973_p2;
wire   [0:0] xor_ln1019_41_fu_979_p2;
wire   [0:0] local_temp_V_21_fu_885_p3;
wire   [0:0] xor_ln1019_42_fu_989_p2;
wire   [0:0] xor_ln1019_43_fu_995_p2;
wire   [0:0] local_temp_V_22_fu_893_p3;
wire   [0:0] xor_ln1019_44_fu_1005_p2;
wire   [0:0] xor_ln1019_45_fu_1011_p2;
wire   [0:0] local_temp_V_23_fu_901_p3;
wire   [0:0] xor_ln1019_46_fu_1021_p2;
wire   [0:0] xor_ln1019_47_fu_1027_p2;
wire   [1:0] zext_ln1019_11_fu_1017_p1;
wire   [1:0] zext_ln1019_10_fu_985_p1;
wire   [1:0] add_ln840_17_fu_1037_p2;
wire   [6:0] zext_ln840_14_fu_1043_p1;
wire   [6:0] zext_ln840_12_fu_1001_p1;
wire   [1:0] zext_ln1019_9_fu_969_p1;
wire   [1:0] zext_ln1019_6_fu_921_p1;
wire   [1:0] add_ln840_19_fu_1053_p2;
wire   [1:0] zext_ln1019_7_fu_937_p1;
wire   [1:0] zext_ln840_13_fu_1033_p1;
wire   [1:0] add_ln840_20_fu_1063_p2;
wire   [1:0] zext_ln1019_8_fu_953_p1;
wire   [1:0] add_ln840_21_fu_1069_p2;
wire   [2:0] zext_ln840_16_fu_1075_p1;
wire   [2:0] zext_ln840_15_fu_1059_p1;
wire   [0:0] local_temp_V_24_fu_1085_p3;
wire   [0:0] xor_ln1019_48_fu_1149_p2;
wire   [0:0] xor_ln1019_49_fu_1155_p2;
wire   [0:0] local_temp_V_25_fu_1093_p3;
wire   [0:0] xor_ln1019_50_fu_1165_p2;
wire   [0:0] xor_ln1019_51_fu_1171_p2;
wire   [0:0] local_temp_V_26_fu_1101_p3;
wire   [0:0] xor_ln1019_52_fu_1181_p2;
wire   [0:0] xor_ln1019_53_fu_1187_p2;
wire   [0:0] local_temp_V_27_fu_1109_p3;
wire   [0:0] xor_ln1019_54_fu_1197_p2;
wire   [0:0] xor_ln1019_55_fu_1203_p2;
wire   [0:0] local_temp_V_28_fu_1117_p3;
wire   [0:0] xor_ln1019_56_fu_1213_p2;
wire   [0:0] xor_ln1019_57_fu_1219_p2;
wire   [0:0] local_temp_V_29_fu_1125_p3;
wire   [0:0] xor_ln1019_58_fu_1229_p2;
wire   [0:0] xor_ln1019_59_fu_1235_p2;
wire   [0:0] local_temp_V_30_fu_1133_p3;
wire   [0:0] xor_ln1019_60_fu_1245_p2;
wire   [0:0] xor_ln1019_61_fu_1251_p2;
wire   [0:0] local_temp_V_31_fu_1141_p3;
wire   [0:0] xor_ln1019_62_fu_1261_p2;
wire   [0:0] xor_ln1019_63_fu_1267_p2;
wire   [1:0] zext_ln1019_17_fu_1257_p1;
wire   [1:0] zext_ln1019_16_fu_1225_p1;
wire   [1:0] add_ln840_25_fu_1277_p2;
wire   [6:0] zext_ln840_20_fu_1283_p1;
wire   [6:0] zext_ln840_18_fu_1241_p1;
wire   [1:0] zext_ln1019_15_fu_1209_p1;
wire   [1:0] zext_ln1019_12_fu_1161_p1;
wire   [1:0] add_ln840_27_fu_1293_p2;
wire   [1:0] zext_ln1019_13_fu_1177_p1;
wire   [1:0] zext_ln840_19_fu_1273_p1;
wire   [1:0] add_ln840_28_fu_1303_p2;
wire   [1:0] zext_ln1019_14_fu_1193_p1;
wire   [1:0] add_ln840_29_fu_1309_p2;
wire   [2:0] zext_ln840_22_fu_1315_p1;
wire   [2:0] zext_ln840_21_fu_1299_p1;
wire   [0:0] local_temp_V_32_fu_1325_p3;
wire   [0:0] xor_ln1019_64_fu_1389_p2;
wire   [0:0] xor_ln1019_65_fu_1395_p2;
wire   [0:0] local_temp_V_33_fu_1333_p3;
wire   [0:0] xor_ln1019_66_fu_1405_p2;
wire   [0:0] xor_ln1019_67_fu_1411_p2;
wire   [0:0] local_temp_V_34_fu_1341_p3;
wire   [0:0] xor_ln1019_68_fu_1421_p2;
wire   [0:0] xor_ln1019_69_fu_1427_p2;
wire   [0:0] local_temp_V_35_fu_1349_p3;
wire   [0:0] xor_ln1019_70_fu_1437_p2;
wire   [0:0] xor_ln1019_71_fu_1443_p2;
wire   [0:0] local_temp_V_36_fu_1357_p3;
wire   [0:0] xor_ln1019_72_fu_1453_p2;
wire   [0:0] xor_ln1019_73_fu_1459_p2;
wire   [0:0] local_temp_V_37_fu_1365_p3;
wire   [0:0] xor_ln1019_74_fu_1469_p2;
wire   [0:0] xor_ln1019_75_fu_1475_p2;
wire   [0:0] local_temp_V_38_fu_1373_p3;
wire   [0:0] xor_ln1019_76_fu_1485_p2;
wire   [0:0] xor_ln1019_77_fu_1491_p2;
wire   [0:0] local_temp_V_39_fu_1381_p3;
wire   [0:0] xor_ln1019_78_fu_1501_p2;
wire   [0:0] xor_ln1019_79_fu_1507_p2;
wire   [1:0] zext_ln1019_23_fu_1497_p1;
wire   [1:0] zext_ln1019_22_fu_1465_p1;
wire   [1:0] add_ln840_33_fu_1517_p2;
wire   [6:0] zext_ln840_26_fu_1523_p1;
wire   [6:0] zext_ln840_24_fu_1481_p1;
wire   [1:0] zext_ln1019_21_fu_1449_p1;
wire   [1:0] zext_ln1019_18_fu_1401_p1;
wire   [1:0] add_ln840_35_fu_1533_p2;
wire   [1:0] zext_ln1019_19_fu_1417_p1;
wire   [1:0] zext_ln840_25_fu_1513_p1;
wire   [1:0] add_ln840_36_fu_1543_p2;
wire   [1:0] zext_ln1019_20_fu_1433_p1;
wire   [1:0] add_ln840_37_fu_1549_p2;
wire   [2:0] zext_ln840_28_fu_1555_p1;
wire   [2:0] zext_ln840_27_fu_1539_p1;
wire   [0:0] local_temp_V_40_fu_1565_p3;
wire   [0:0] xor_ln1019_80_fu_1629_p2;
wire   [0:0] xor_ln1019_81_fu_1635_p2;
wire   [0:0] local_temp_V_41_fu_1573_p3;
wire   [0:0] xor_ln1019_82_fu_1645_p2;
wire   [0:0] xor_ln1019_83_fu_1651_p2;
wire   [0:0] local_temp_V_42_fu_1581_p3;
wire   [0:0] xor_ln1019_84_fu_1661_p2;
wire   [0:0] xor_ln1019_85_fu_1667_p2;
wire   [0:0] local_temp_V_43_fu_1589_p3;
wire   [0:0] xor_ln1019_86_fu_1677_p2;
wire   [0:0] xor_ln1019_87_fu_1683_p2;
wire   [0:0] local_temp_V_44_fu_1597_p3;
wire   [0:0] xor_ln1019_88_fu_1693_p2;
wire   [0:0] xor_ln1019_89_fu_1699_p2;
wire   [0:0] local_temp_V_45_fu_1605_p3;
wire   [0:0] xor_ln1019_90_fu_1709_p2;
wire   [0:0] xor_ln1019_91_fu_1715_p2;
wire   [0:0] local_temp_V_46_fu_1613_p3;
wire   [0:0] xor_ln1019_92_fu_1725_p2;
wire   [0:0] xor_ln1019_93_fu_1731_p2;
wire   [0:0] local_temp_V_47_fu_1621_p3;
wire   [0:0] xor_ln1019_94_fu_1741_p2;
wire   [0:0] xor_ln1019_95_fu_1747_p2;
wire   [1:0] zext_ln1019_29_fu_1737_p1;
wire   [1:0] zext_ln1019_28_fu_1705_p1;
wire   [1:0] add_ln840_41_fu_1757_p2;
wire   [6:0] zext_ln840_32_fu_1763_p1;
wire   [6:0] zext_ln840_30_fu_1721_p1;
wire   [1:0] zext_ln1019_27_fu_1689_p1;
wire   [1:0] zext_ln1019_24_fu_1641_p1;
wire   [1:0] add_ln840_43_fu_1773_p2;
wire   [1:0] zext_ln1019_25_fu_1657_p1;
wire   [1:0] zext_ln840_31_fu_1753_p1;
wire   [1:0] add_ln840_44_fu_1783_p2;
wire   [1:0] zext_ln1019_26_fu_1673_p1;
wire   [1:0] add_ln840_45_fu_1789_p2;
wire   [2:0] zext_ln840_34_fu_1795_p1;
wire   [2:0] zext_ln840_33_fu_1779_p1;
wire   [0:0] local_temp_V_48_fu_1805_p3;
wire   [0:0] xor_ln1019_96_fu_1869_p2;
wire   [0:0] xor_ln1019_97_fu_1875_p2;
wire   [0:0] local_temp_V_49_fu_1813_p3;
wire   [0:0] xor_ln1019_98_fu_1885_p2;
wire   [0:0] xor_ln1019_99_fu_1891_p2;
wire   [0:0] local_temp_V_50_fu_1821_p3;
wire   [0:0] xor_ln1019_100_fu_1901_p2;
wire   [0:0] xor_ln1019_101_fu_1907_p2;
wire   [0:0] local_temp_V_51_fu_1829_p3;
wire   [0:0] xor_ln1019_102_fu_1917_p2;
wire   [0:0] xor_ln1019_103_fu_1923_p2;
wire   [0:0] local_temp_V_52_fu_1837_p3;
wire   [0:0] xor_ln1019_104_fu_1933_p2;
wire   [0:0] xor_ln1019_105_fu_1939_p2;
wire   [0:0] local_temp_V_53_fu_1845_p3;
wire   [0:0] xor_ln1019_106_fu_1949_p2;
wire   [0:0] xor_ln1019_107_fu_1955_p2;
wire   [0:0] local_temp_V_54_fu_1853_p3;
wire   [0:0] xor_ln1019_108_fu_1965_p2;
wire   [0:0] xor_ln1019_109_fu_1971_p2;
wire   [0:0] local_temp_V_55_fu_1861_p3;
wire   [0:0] xor_ln1019_110_fu_1981_p2;
wire   [0:0] xor_ln1019_111_fu_1987_p2;
wire   [1:0] zext_ln1019_35_fu_1977_p1;
wire   [1:0] zext_ln1019_34_fu_1945_p1;
wire   [1:0] add_ln840_49_fu_1997_p2;
wire   [6:0] zext_ln840_38_fu_2003_p1;
wire   [6:0] zext_ln840_36_fu_1961_p1;
wire   [1:0] zext_ln1019_33_fu_1929_p1;
wire   [1:0] zext_ln1019_30_fu_1881_p1;
wire   [1:0] add_ln840_51_fu_2013_p2;
wire   [1:0] zext_ln1019_31_fu_1897_p1;
wire   [1:0] zext_ln840_37_fu_1993_p1;
wire   [1:0] add_ln840_52_fu_2023_p2;
wire   [1:0] zext_ln1019_32_fu_1913_p1;
wire   [1:0] add_ln840_53_fu_2029_p2;
wire   [2:0] zext_ln840_40_fu_2035_p1;
wire   [2:0] zext_ln840_39_fu_2019_p1;
wire   [0:0] local_temp_V_56_fu_2045_p3;
wire   [0:0] xor_ln1019_112_fu_2109_p2;
wire   [0:0] xor_ln1019_113_fu_2115_p2;
wire   [0:0] local_temp_V_57_fu_2053_p3;
wire   [0:0] xor_ln1019_114_fu_2125_p2;
wire   [0:0] xor_ln1019_115_fu_2131_p2;
wire   [0:0] local_temp_V_58_fu_2061_p3;
wire   [0:0] xor_ln1019_116_fu_2141_p2;
wire   [0:0] xor_ln1019_117_fu_2147_p2;
wire   [0:0] local_temp_V_59_fu_2069_p3;
wire   [0:0] xor_ln1019_118_fu_2157_p2;
wire   [0:0] xor_ln1019_119_fu_2163_p2;
wire   [0:0] local_temp_V_60_fu_2077_p3;
wire   [0:0] xor_ln1019_120_fu_2173_p2;
wire   [0:0] xor_ln1019_121_fu_2179_p2;
wire   [0:0] local_temp_V_61_fu_2085_p3;
wire   [0:0] xor_ln1019_122_fu_2189_p2;
wire   [0:0] xor_ln1019_123_fu_2195_p2;
wire   [0:0] local_temp_V_62_fu_2093_p3;
wire   [0:0] xor_ln1019_124_fu_2205_p2;
wire   [0:0] xor_ln1019_125_fu_2211_p2;
wire   [0:0] local_temp_V_63_fu_2101_p3;
wire   [0:0] xor_ln1019_126_fu_2221_p2;
wire   [0:0] xor_ln1019_127_fu_2227_p2;
wire   [1:0] zext_ln1019_41_fu_2217_p1;
wire   [1:0] zext_ln1019_40_fu_2185_p1;
wire   [1:0] add_ln840_57_fu_2237_p2;
wire   [6:0] zext_ln840_44_fu_2243_p1;
wire   [6:0] zext_ln840_42_fu_2201_p1;
wire   [1:0] zext_ln1019_39_fu_2169_p1;
wire   [1:0] zext_ln1019_36_fu_2121_p1;
wire   [1:0] add_ln840_59_fu_2253_p2;
wire   [1:0] zext_ln1019_37_fu_2137_p1;
wire   [1:0] zext_ln840_43_fu_2233_p1;
wire   [1:0] add_ln840_60_fu_2263_p2;
wire   [1:0] zext_ln1019_38_fu_2153_p1;
wire   [1:0] add_ln840_61_fu_2269_p2;
wire   [2:0] zext_ln840_46_fu_2275_p1;
wire   [2:0] zext_ln840_45_fu_2259_p1;
wire   [0:0] local_temp_V_64_fu_2285_p3;
wire   [0:0] xor_ln1019_128_fu_2349_p2;
wire   [0:0] xor_ln1019_129_fu_2355_p2;
wire   [0:0] local_temp_V_65_fu_2293_p3;
wire   [0:0] xor_ln1019_130_fu_2365_p2;
wire   [0:0] xor_ln1019_131_fu_2371_p2;
wire   [0:0] local_temp_V_66_fu_2301_p3;
wire   [0:0] xor_ln1019_132_fu_2381_p2;
wire   [0:0] xor_ln1019_133_fu_2387_p2;
wire   [0:0] local_temp_V_67_fu_2309_p3;
wire   [0:0] xor_ln1019_134_fu_2397_p2;
wire   [0:0] xor_ln1019_135_fu_2403_p2;
wire   [0:0] local_temp_V_68_fu_2317_p3;
wire   [0:0] xor_ln1019_136_fu_2413_p2;
wire   [0:0] xor_ln1019_137_fu_2419_p2;
wire   [0:0] local_temp_V_69_fu_2325_p3;
wire   [0:0] xor_ln1019_138_fu_2429_p2;
wire   [0:0] xor_ln1019_139_fu_2435_p2;
wire   [0:0] local_temp_V_70_fu_2333_p3;
wire   [0:0] xor_ln1019_140_fu_2445_p2;
wire   [0:0] xor_ln1019_141_fu_2451_p2;
wire   [0:0] local_temp_V_71_fu_2341_p3;
wire   [0:0] xor_ln1019_142_fu_2461_p2;
wire   [0:0] xor_ln1019_143_fu_2467_p2;
wire   [1:0] zext_ln1019_47_fu_2457_p1;
wire   [1:0] zext_ln1019_46_fu_2425_p1;
wire   [1:0] add_ln840_65_fu_2477_p2;
wire   [6:0] zext_ln840_50_fu_2483_p1;
wire   [6:0] zext_ln840_48_fu_2441_p1;
wire   [1:0] zext_ln1019_45_fu_2409_p1;
wire   [1:0] zext_ln1019_42_fu_2361_p1;
wire   [1:0] add_ln840_67_fu_2493_p2;
wire   [1:0] zext_ln1019_43_fu_2377_p1;
wire   [1:0] zext_ln840_49_fu_2473_p1;
wire   [1:0] add_ln840_68_fu_2503_p2;
wire   [1:0] zext_ln1019_44_fu_2393_p1;
wire   [1:0] add_ln840_69_fu_2509_p2;
wire   [2:0] zext_ln840_52_fu_2515_p1;
wire   [2:0] zext_ln840_51_fu_2499_p1;
wire   [0:0] local_temp_V_72_fu_2525_p3;
wire   [0:0] xor_ln1019_144_fu_2589_p2;
wire   [0:0] xor_ln1019_145_fu_2595_p2;
wire   [0:0] local_temp_V_73_fu_2533_p3;
wire   [0:0] xor_ln1019_146_fu_2605_p2;
wire   [0:0] xor_ln1019_147_fu_2611_p2;
wire   [0:0] local_temp_V_74_fu_2541_p3;
wire   [0:0] xor_ln1019_148_fu_2621_p2;
wire   [0:0] xor_ln1019_149_fu_2627_p2;
wire   [0:0] local_temp_V_75_fu_2549_p3;
wire   [0:0] xor_ln1019_150_fu_2637_p2;
wire   [0:0] xor_ln1019_151_fu_2643_p2;
wire   [0:0] local_temp_V_76_fu_2557_p3;
wire   [0:0] xor_ln1019_152_fu_2653_p2;
wire   [0:0] xor_ln1019_153_fu_2659_p2;
wire   [0:0] local_temp_V_77_fu_2565_p3;
wire   [0:0] xor_ln1019_154_fu_2669_p2;
wire   [0:0] xor_ln1019_155_fu_2675_p2;
wire   [0:0] local_temp_V_78_fu_2573_p3;
wire   [0:0] xor_ln1019_156_fu_2685_p2;
wire   [0:0] xor_ln1019_157_fu_2691_p2;
wire   [0:0] local_temp_V_79_fu_2581_p3;
wire   [0:0] xor_ln1019_158_fu_2701_p2;
wire   [0:0] xor_ln1019_159_fu_2707_p2;
wire   [1:0] zext_ln1019_53_fu_2697_p1;
wire   [1:0] zext_ln1019_52_fu_2665_p1;
wire   [1:0] add_ln840_73_fu_2717_p2;
wire   [6:0] zext_ln840_56_fu_2723_p1;
wire   [6:0] zext_ln840_54_fu_2681_p1;
wire   [1:0] zext_ln1019_51_fu_2649_p1;
wire   [1:0] zext_ln1019_48_fu_2601_p1;
wire   [1:0] add_ln840_75_fu_2733_p2;
wire   [1:0] zext_ln1019_49_fu_2617_p1;
wire   [1:0] zext_ln840_55_fu_2713_p1;
wire   [1:0] add_ln840_76_fu_2743_p2;
wire   [1:0] zext_ln1019_50_fu_2633_p1;
wire   [1:0] add_ln840_77_fu_2749_p2;
wire   [2:0] zext_ln840_58_fu_2755_p1;
wire   [2:0] zext_ln840_57_fu_2739_p1;
wire   [6:0] select_ln272_9_fu_2885_p3;
wire   [6:0] zext_ln840_5_fu_2897_p1;
wire   [6:0] add_ln840_2_fu_2892_p2;
wire   [6:0] select_ln272_8_fu_2878_p3;
wire   [6:0] zext_ln840_11_fu_2911_p1;
wire   [6:0] add_ln840_10_fu_2906_p2;
wire   [6:0] select_ln272_7_fu_2871_p3;
wire   [6:0] zext_ln840_17_fu_2925_p1;
wire   [6:0] add_ln840_18_fu_2920_p2;
wire   [6:0] select_ln272_6_fu_2864_p3;
wire   [6:0] zext_ln840_23_fu_2939_p1;
wire   [6:0] add_ln840_26_fu_2934_p2;
wire   [6:0] select_ln272_5_fu_2857_p3;
wire   [6:0] zext_ln840_29_fu_2953_p1;
wire   [6:0] add_ln840_34_fu_2948_p2;
wire   [6:0] select_ln272_4_fu_2850_p3;
wire   [6:0] zext_ln840_35_fu_2967_p1;
wire   [6:0] add_ln840_42_fu_2962_p2;
wire   [6:0] select_ln272_3_fu_2843_p3;
wire   [6:0] zext_ln840_41_fu_2981_p1;
wire   [6:0] add_ln840_50_fu_2976_p2;
wire   [6:0] select_ln272_2_fu_2836_p3;
wire   [6:0] zext_ln840_47_fu_2995_p1;
wire   [6:0] add_ln840_58_fu_2990_p2;
wire   [6:0] select_ln272_1_fu_2829_p3;
wire   [6:0] zext_ln840_53_fu_3009_p1;
wire   [6:0] add_ln840_66_fu_3004_p2;
wire   [6:0] select_ln272_fu_2822_p3;
wire   [6:0] zext_ln840_59_fu_3023_p1;
wire   [6:0] add_ln840_74_fu_3018_p2;
wire   [69:0] p_Result_9_fu_3032_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_start_int;
reg    ap_condition_2141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

MatrixVectorActivation_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2141)) begin
        if ((icmp_ln249_fu_294_p2 == 1'd0)) begin
            i_fu_212 <= i_2_fu_288_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_212 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2141)) begin
        if (((icmp_ln249_fu_294_p2 == 1'd0) & (icmp_ln290_fu_2771_p2 == 1'd1))) begin
            sf_fu_208 <= 32'd0;
        end else if (((icmp_ln249_fu_294_p2 == 1'd0) & (icmp_ln290_fu_2771_p2 == 1'd0))) begin
            sf_fu_208 <= sf_1_fu_2765_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_208 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_3186 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        add_i_i_i2_1_7140_fu_220 <= add_ln840_15_fu_2914_p2;
        add_i_i_i2_2_7142_fu_224 <= add_ln840_23_fu_2928_p2;
        add_i_i_i2_3_7144_fu_228 <= add_ln840_31_fu_2942_p2;
        add_i_i_i2_4_7146_fu_232 <= add_ln840_39_fu_2956_p2;
        add_i_i_i2_5_7148_fu_236 <= add_ln840_47_fu_2970_p2;
        add_i_i_i2_6_7150_fu_240 <= add_ln840_55_fu_2984_p2;
        add_i_i_i2_775138_fu_216 <= add_ln840_7_fu_2900_p2;
        add_i_i_i2_7_7152_fu_244 <= add_ln840_63_fu_2998_p2;
        add_i_i_i2_8_7154_fu_248 <= add_ln840_71_fu_3012_p2;
        add_i_i_i2_9_7156_fu_252 <= add_ln840_79_fu_3026_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_ln840_14_reg_3219 <= add_ln840_14_fu_839_p2;
        add_ln840_16_reg_3224 <= add_ln840_16_fu_1047_p2;
        add_ln840_22_reg_3229 <= add_ln840_22_fu_1079_p2;
        add_ln840_24_reg_3234 <= add_ln840_24_fu_1287_p2;
        add_ln840_30_reg_3239 <= add_ln840_30_fu_1319_p2;
        add_ln840_32_reg_3244 <= add_ln840_32_fu_1527_p2;
        add_ln840_38_reg_3249 <= add_ln840_38_fu_1559_p2;
        add_ln840_40_reg_3254 <= add_ln840_40_fu_1767_p2;
        add_ln840_46_reg_3259 <= add_ln840_46_fu_1799_p2;
        add_ln840_48_reg_3264 <= add_ln840_48_fu_2007_p2;
        add_ln840_54_reg_3269 <= add_ln840_54_fu_2039_p2;
        add_ln840_56_reg_3274 <= add_ln840_56_fu_2247_p2;
        add_ln840_62_reg_3279 <= add_ln840_62_fu_2279_p2;
        add_ln840_64_reg_3284 <= add_ln840_64_fu_2487_p2;
        add_ln840_6_reg_3209 <= add_ln840_6_fu_599_p2;
        add_ln840_70_reg_3289 <= add_ln840_70_fu_2519_p2;
        add_ln840_72_reg_3294 <= add_ln840_72_fu_2727_p2;
        add_ln840_78_reg_3299 <= add_ln840_78_fu_2759_p2;
        add_ln840_8_reg_3214 <= add_ln840_8_fu_807_p2;
        add_ln840_reg_3204 <= add_ln840_fu_567_p2;
        icmp_ln272_reg_3190 <= icmp_ln272_fu_307_p2;
        icmp_ln290_reg_3304 <= icmp_ln290_fu_2771_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln249_reg_3186 <= icmp_ln249_fu_294_p2;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_294_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_212;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_load = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_load = sf_fu_208;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op511_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op511_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else if (((~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_3186_pp0_iter0_reg == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln840_10_fu_2906_p2 = (add_ln840_8_reg_3214 + select_ln272_8_fu_2878_p3);

assign add_ln840_11_fu_813_p2 = (zext_ln1019_3_fu_729_p1 + zext_ln1019_fu_681_p1);

assign add_ln840_12_fu_823_p2 = (zext_ln1019_1_fu_697_p1 + zext_ln840_7_fu_793_p1);

assign add_ln840_13_fu_829_p2 = (add_ln840_12_fu_823_p2 + zext_ln1019_2_fu_713_p1);

assign add_ln840_14_fu_839_p2 = (zext_ln840_10_fu_835_p1 + zext_ln840_9_fu_819_p1);

assign add_ln840_15_fu_2914_p2 = (zext_ln840_11_fu_2911_p1 + add_ln840_10_fu_2906_p2);

assign add_ln840_16_fu_1047_p2 = (zext_ln840_14_fu_1043_p1 + zext_ln840_12_fu_1001_p1);

assign add_ln840_17_fu_1037_p2 = (zext_ln1019_11_fu_1017_p1 + zext_ln1019_10_fu_985_p1);

assign add_ln840_18_fu_2920_p2 = (add_ln840_16_reg_3224 + select_ln272_7_fu_2871_p3);

assign add_ln840_19_fu_1053_p2 = (zext_ln1019_9_fu_969_p1 + zext_ln1019_6_fu_921_p1);

assign add_ln840_1_fu_557_p2 = (zext_ln780_5_fu_529_p1 + zext_ln780_4_fu_481_p1);

assign add_ln840_20_fu_1063_p2 = (zext_ln1019_7_fu_937_p1 + zext_ln840_13_fu_1033_p1);

assign add_ln840_21_fu_1069_p2 = (add_ln840_20_fu_1063_p2 + zext_ln1019_8_fu_953_p1);

assign add_ln840_22_fu_1079_p2 = (zext_ln840_16_fu_1075_p1 + zext_ln840_15_fu_1059_p1);

assign add_ln840_23_fu_2928_p2 = (zext_ln840_17_fu_2925_p1 + add_ln840_18_fu_2920_p2);

assign add_ln840_24_fu_1287_p2 = (zext_ln840_20_fu_1283_p1 + zext_ln840_18_fu_1241_p1);

assign add_ln840_25_fu_1277_p2 = (zext_ln1019_17_fu_1257_p1 + zext_ln1019_16_fu_1225_p1);

assign add_ln840_26_fu_2934_p2 = (add_ln840_24_reg_3234 + select_ln272_6_fu_2864_p3);

assign add_ln840_27_fu_1293_p2 = (zext_ln1019_15_fu_1209_p1 + zext_ln1019_12_fu_1161_p1);

assign add_ln840_28_fu_1303_p2 = (zext_ln1019_13_fu_1177_p1 + zext_ln840_19_fu_1273_p1);

assign add_ln840_29_fu_1309_p2 = (add_ln840_28_fu_1303_p2 + zext_ln1019_14_fu_1193_p1);

assign add_ln840_2_fu_2892_p2 = (add_ln840_reg_3204 + select_ln272_9_fu_2885_p3);

assign add_ln840_30_fu_1319_p2 = (zext_ln840_22_fu_1315_p1 + zext_ln840_21_fu_1299_p1);

assign add_ln840_31_fu_2942_p2 = (zext_ln840_23_fu_2939_p1 + add_ln840_26_fu_2934_p2);

assign add_ln840_32_fu_1527_p2 = (zext_ln840_26_fu_1523_p1 + zext_ln840_24_fu_1481_p1);

assign add_ln840_33_fu_1517_p2 = (zext_ln1019_23_fu_1497_p1 + zext_ln1019_22_fu_1465_p1);

assign add_ln840_34_fu_2948_p2 = (add_ln840_32_reg_3244 + select_ln272_5_fu_2857_p3);

assign add_ln840_35_fu_1533_p2 = (zext_ln1019_21_fu_1449_p1 + zext_ln1019_18_fu_1401_p1);

assign add_ln840_36_fu_1543_p2 = (zext_ln1019_19_fu_1417_p1 + zext_ln840_25_fu_1513_p1);

assign add_ln840_37_fu_1549_p2 = (add_ln840_36_fu_1543_p2 + zext_ln1019_20_fu_1433_p1);

assign add_ln840_38_fu_1559_p2 = (zext_ln840_28_fu_1555_p1 + zext_ln840_27_fu_1539_p1);

assign add_ln840_39_fu_2956_p2 = (zext_ln840_29_fu_2953_p1 + add_ln840_34_fu_2948_p2);

assign add_ln840_3_fu_573_p2 = (zext_ln780_3_fu_457_p1 + zext_ln780_fu_385_p1);

assign add_ln840_40_fu_1767_p2 = (zext_ln840_32_fu_1763_p1 + zext_ln840_30_fu_1721_p1);

assign add_ln840_41_fu_1757_p2 = (zext_ln1019_29_fu_1737_p1 + zext_ln1019_28_fu_1705_p1);

assign add_ln840_42_fu_2962_p2 = (add_ln840_40_reg_3254 + select_ln272_4_fu_2850_p3);

assign add_ln840_43_fu_1773_p2 = (zext_ln1019_27_fu_1689_p1 + zext_ln1019_24_fu_1641_p1);

assign add_ln840_44_fu_1783_p2 = (zext_ln1019_25_fu_1657_p1 + zext_ln840_31_fu_1753_p1);

assign add_ln840_45_fu_1789_p2 = (add_ln840_44_fu_1783_p2 + zext_ln1019_26_fu_1673_p1);

assign add_ln840_46_fu_1799_p2 = (zext_ln840_34_fu_1795_p1 + zext_ln840_33_fu_1779_p1);

assign add_ln840_47_fu_2970_p2 = (zext_ln840_35_fu_2967_p1 + add_ln840_42_fu_2962_p2);

assign add_ln840_48_fu_2007_p2 = (zext_ln840_38_fu_2003_p1 + zext_ln840_36_fu_1961_p1);

assign add_ln840_49_fu_1997_p2 = (zext_ln1019_35_fu_1977_p1 + zext_ln1019_34_fu_1945_p1);

assign add_ln840_4_fu_583_p2 = (zext_ln780_1_fu_409_p1 + zext_ln840_1_fu_553_p1);

assign add_ln840_50_fu_2976_p2 = (add_ln840_48_reg_3264 + select_ln272_3_fu_2843_p3);

assign add_ln840_51_fu_2013_p2 = (zext_ln1019_33_fu_1929_p1 + zext_ln1019_30_fu_1881_p1);

assign add_ln840_52_fu_2023_p2 = (zext_ln1019_31_fu_1897_p1 + zext_ln840_37_fu_1993_p1);

assign add_ln840_53_fu_2029_p2 = (add_ln840_52_fu_2023_p2 + zext_ln1019_32_fu_1913_p1);

assign add_ln840_54_fu_2039_p2 = (zext_ln840_40_fu_2035_p1 + zext_ln840_39_fu_2019_p1);

assign add_ln840_55_fu_2984_p2 = (zext_ln840_41_fu_2981_p1 + add_ln840_50_fu_2976_p2);

assign add_ln840_56_fu_2247_p2 = (zext_ln840_44_fu_2243_p1 + zext_ln840_42_fu_2201_p1);

assign add_ln840_57_fu_2237_p2 = (zext_ln1019_41_fu_2217_p1 + zext_ln1019_40_fu_2185_p1);

assign add_ln840_58_fu_2990_p2 = (add_ln840_56_reg_3274 + select_ln272_2_fu_2836_p3);

assign add_ln840_59_fu_2253_p2 = (zext_ln1019_39_fu_2169_p1 + zext_ln1019_36_fu_2121_p1);

assign add_ln840_5_fu_589_p2 = (add_ln840_4_fu_583_p2 + zext_ln780_2_fu_433_p1);

assign add_ln840_60_fu_2263_p2 = (zext_ln1019_37_fu_2137_p1 + zext_ln840_43_fu_2233_p1);

assign add_ln840_61_fu_2269_p2 = (add_ln840_60_fu_2263_p2 + zext_ln1019_38_fu_2153_p1);

assign add_ln840_62_fu_2279_p2 = (zext_ln840_46_fu_2275_p1 + zext_ln840_45_fu_2259_p1);

assign add_ln840_63_fu_2998_p2 = (zext_ln840_47_fu_2995_p1 + add_ln840_58_fu_2990_p2);

assign add_ln840_64_fu_2487_p2 = (zext_ln840_50_fu_2483_p1 + zext_ln840_48_fu_2441_p1);

assign add_ln840_65_fu_2477_p2 = (zext_ln1019_47_fu_2457_p1 + zext_ln1019_46_fu_2425_p1);

assign add_ln840_66_fu_3004_p2 = (add_ln840_64_reg_3284 + select_ln272_1_fu_2829_p3);

assign add_ln840_67_fu_2493_p2 = (zext_ln1019_45_fu_2409_p1 + zext_ln1019_42_fu_2361_p1);

assign add_ln840_68_fu_2503_p2 = (zext_ln1019_43_fu_2377_p1 + zext_ln840_49_fu_2473_p1);

assign add_ln840_69_fu_2509_p2 = (add_ln840_68_fu_2503_p2 + zext_ln1019_44_fu_2393_p1);

assign add_ln840_6_fu_599_p2 = (zext_ln840_4_fu_595_p1 + zext_ln840_3_fu_579_p1);

assign add_ln840_70_fu_2519_p2 = (zext_ln840_52_fu_2515_p1 + zext_ln840_51_fu_2499_p1);

assign add_ln840_71_fu_3012_p2 = (zext_ln840_53_fu_3009_p1 + add_ln840_66_fu_3004_p2);

assign add_ln840_72_fu_2727_p2 = (zext_ln840_56_fu_2723_p1 + zext_ln840_54_fu_2681_p1);

assign add_ln840_73_fu_2717_p2 = (zext_ln1019_53_fu_2697_p1 + zext_ln1019_52_fu_2665_p1);

assign add_ln840_74_fu_3018_p2 = (add_ln840_72_reg_3294 + select_ln272_fu_2822_p3);

assign add_ln840_75_fu_2733_p2 = (zext_ln1019_51_fu_2649_p1 + zext_ln1019_48_fu_2601_p1);

assign add_ln840_76_fu_2743_p2 = (zext_ln1019_49_fu_2617_p1 + zext_ln840_55_fu_2713_p1);

assign add_ln840_77_fu_2749_p2 = (add_ln840_76_fu_2743_p2 + zext_ln1019_50_fu_2633_p1);

assign add_ln840_78_fu_2759_p2 = (zext_ln840_58_fu_2755_p1 + zext_ln840_57_fu_2739_p1);

assign add_ln840_79_fu_3026_p2 = (zext_ln840_59_fu_3023_p1 + add_ln840_74_fu_3018_p2);

assign add_ln840_7_fu_2900_p2 = (zext_ln840_5_fu_2897_p1 + add_ln840_2_fu_2892_p2);

assign add_ln840_8_fu_807_p2 = (zext_ln840_8_fu_803_p1 + zext_ln840_6_fu_761_p1);

assign add_ln840_9_fu_797_p2 = (zext_ln1019_5_fu_777_p1 + zext_ln1019_4_fu_745_p1);

assign add_ln840_fu_567_p2 = (zext_ln840_2_fu_563_p1 + zext_ln840_fu_505_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_2141 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((ap_predicate_op511_write_state2 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_294_p2 == 1'd0)) | ((icmp_ln249_fu_294_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op511_write_state2 = ((icmp_ln290_reg_3304 == 1'd1) & (icmp_ln249_reg_3186 == 1'd0));
end

assign i_2_fu_288_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign icmp_ln249_fu_294_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_3186_pp0_iter0_reg = icmp_ln249_reg_3186;

assign icmp_ln272_fu_307_p2 = ((ap_sig_allocacmp_sf_load == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_2771_p2 = ((sf_1_fu_2765_p2 == 32'd8) ? 1'b1 : 1'b0);

assign local_temp_V_10_fu_621_p3 = weights_V_TDATA[32'd10];

assign local_temp_V_11_fu_629_p3 = weights_V_TDATA[32'd11];

assign local_temp_V_12_fu_637_p3 = weights_V_TDATA[32'd12];

assign local_temp_V_13_fu_645_p3 = weights_V_TDATA[32'd13];

assign local_temp_V_14_fu_653_p3 = weights_V_TDATA[32'd14];

assign local_temp_V_15_fu_661_p3 = weights_V_TDATA[32'd15];

assign local_temp_V_16_fu_845_p3 = weights_V_TDATA[32'd16];

assign local_temp_V_17_fu_853_p3 = weights_V_TDATA[32'd17];

assign local_temp_V_18_fu_861_p3 = weights_V_TDATA[32'd18];

assign local_temp_V_19_fu_869_p3 = weights_V_TDATA[32'd19];

assign local_temp_V_1_fu_317_p3 = weights_V_TDATA[32'd1];

assign local_temp_V_20_fu_877_p3 = weights_V_TDATA[32'd20];

assign local_temp_V_21_fu_885_p3 = weights_V_TDATA[32'd21];

assign local_temp_V_22_fu_893_p3 = weights_V_TDATA[32'd22];

assign local_temp_V_23_fu_901_p3 = weights_V_TDATA[32'd23];

assign local_temp_V_24_fu_1085_p3 = weights_V_TDATA[32'd24];

assign local_temp_V_25_fu_1093_p3 = weights_V_TDATA[32'd25];

assign local_temp_V_26_fu_1101_p3 = weights_V_TDATA[32'd26];

assign local_temp_V_27_fu_1109_p3 = weights_V_TDATA[32'd27];

assign local_temp_V_28_fu_1117_p3 = weights_V_TDATA[32'd28];

assign local_temp_V_29_fu_1125_p3 = weights_V_TDATA[32'd29];

assign local_temp_V_2_fu_325_p3 = weights_V_TDATA[32'd2];

assign local_temp_V_30_fu_1133_p3 = weights_V_TDATA[32'd30];

assign local_temp_V_31_fu_1141_p3 = weights_V_TDATA[32'd31];

assign local_temp_V_32_fu_1325_p3 = weights_V_TDATA[32'd32];

assign local_temp_V_33_fu_1333_p3 = weights_V_TDATA[32'd33];

assign local_temp_V_34_fu_1341_p3 = weights_V_TDATA[32'd34];

assign local_temp_V_35_fu_1349_p3 = weights_V_TDATA[32'd35];

assign local_temp_V_36_fu_1357_p3 = weights_V_TDATA[32'd36];

assign local_temp_V_37_fu_1365_p3 = weights_V_TDATA[32'd37];

assign local_temp_V_38_fu_1373_p3 = weights_V_TDATA[32'd38];

assign local_temp_V_39_fu_1381_p3 = weights_V_TDATA[32'd39];

assign local_temp_V_3_fu_333_p3 = weights_V_TDATA[32'd3];

assign local_temp_V_40_fu_1565_p3 = weights_V_TDATA[32'd40];

assign local_temp_V_41_fu_1573_p3 = weights_V_TDATA[32'd41];

assign local_temp_V_42_fu_1581_p3 = weights_V_TDATA[32'd42];

assign local_temp_V_43_fu_1589_p3 = weights_V_TDATA[32'd43];

assign local_temp_V_44_fu_1597_p3 = weights_V_TDATA[32'd44];

assign local_temp_V_45_fu_1605_p3 = weights_V_TDATA[32'd45];

assign local_temp_V_46_fu_1613_p3 = weights_V_TDATA[32'd46];

assign local_temp_V_47_fu_1621_p3 = weights_V_TDATA[32'd47];

assign local_temp_V_48_fu_1805_p3 = weights_V_TDATA[32'd48];

assign local_temp_V_49_fu_1813_p3 = weights_V_TDATA[32'd49];

assign local_temp_V_4_fu_341_p3 = weights_V_TDATA[32'd4];

assign local_temp_V_50_fu_1821_p3 = weights_V_TDATA[32'd50];

assign local_temp_V_51_fu_1829_p3 = weights_V_TDATA[32'd51];

assign local_temp_V_52_fu_1837_p3 = weights_V_TDATA[32'd52];

assign local_temp_V_53_fu_1845_p3 = weights_V_TDATA[32'd53];

assign local_temp_V_54_fu_1853_p3 = weights_V_TDATA[32'd54];

assign local_temp_V_55_fu_1861_p3 = weights_V_TDATA[32'd55];

assign local_temp_V_56_fu_2045_p3 = weights_V_TDATA[32'd56];

assign local_temp_V_57_fu_2053_p3 = weights_V_TDATA[32'd57];

assign local_temp_V_58_fu_2061_p3 = weights_V_TDATA[32'd58];

assign local_temp_V_59_fu_2069_p3 = weights_V_TDATA[32'd59];

assign local_temp_V_5_fu_349_p3 = weights_V_TDATA[32'd5];

assign local_temp_V_60_fu_2077_p3 = weights_V_TDATA[32'd60];

assign local_temp_V_61_fu_2085_p3 = weights_V_TDATA[32'd61];

assign local_temp_V_62_fu_2093_p3 = weights_V_TDATA[32'd62];

assign local_temp_V_63_fu_2101_p3 = weights_V_TDATA[32'd63];

assign local_temp_V_64_fu_2285_p3 = weights_V_TDATA[32'd64];

assign local_temp_V_65_fu_2293_p3 = weights_V_TDATA[32'd65];

assign local_temp_V_66_fu_2301_p3 = weights_V_TDATA[32'd66];

assign local_temp_V_67_fu_2309_p3 = weights_V_TDATA[32'd67];

assign local_temp_V_68_fu_2317_p3 = weights_V_TDATA[32'd68];

assign local_temp_V_69_fu_2325_p3 = weights_V_TDATA[32'd69];

assign local_temp_V_6_fu_357_p3 = weights_V_TDATA[32'd6];

assign local_temp_V_70_fu_2333_p3 = weights_V_TDATA[32'd70];

assign local_temp_V_71_fu_2341_p3 = weights_V_TDATA[32'd71];

assign local_temp_V_72_fu_2525_p3 = weights_V_TDATA[32'd72];

assign local_temp_V_73_fu_2533_p3 = weights_V_TDATA[32'd73];

assign local_temp_V_74_fu_2541_p3 = weights_V_TDATA[32'd74];

assign local_temp_V_75_fu_2549_p3 = weights_V_TDATA[32'd75];

assign local_temp_V_76_fu_2557_p3 = weights_V_TDATA[32'd76];

assign local_temp_V_77_fu_2565_p3 = weights_V_TDATA[32'd77];

assign local_temp_V_78_fu_2573_p3 = weights_V_TDATA[32'd78];

assign local_temp_V_79_fu_2581_p3 = weights_V_TDATA[32'd79];

assign local_temp_V_7_fu_365_p3 = weights_V_TDATA[32'd7];

assign local_temp_V_8_fu_605_p3 = weights_V_TDATA[32'd8];

assign local_temp_V_9_fu_613_p3 = weights_V_TDATA[32'd9];

assign local_temp_V_fu_313_p1 = weights_V_TDATA[0:0];

assign out_V_TDATA = p_Result_9_fu_3032_p11;

assign p_Result_1_fu_389_p3 = in0_V_TDATA[32'd1];

assign p_Result_2_fu_413_p3 = in0_V_TDATA[32'd2];

assign p_Result_3_fu_437_p3 = in0_V_TDATA[32'd3];

assign p_Result_4_fu_461_p3 = in0_V_TDATA[32'd4];

assign p_Result_5_fu_485_p3 = in0_V_TDATA[32'd5];

assign p_Result_6_fu_509_p3 = in0_V_TDATA[32'd6];

assign p_Result_7_fu_533_p3 = in0_V_TDATA[32'd7];

assign p_Result_9_fu_3032_p11 = {{{{{{{{{{add_ln840_79_fu_3026_p2}, {add_ln840_71_fu_3012_p2}}, {add_ln840_63_fu_2998_p2}}, {add_ln840_55_fu_2984_p2}}, {add_ln840_47_fu_2970_p2}}, {add_ln840_39_fu_2956_p2}}, {add_ln840_31_fu_2942_p2}}, {add_ln840_23_fu_2928_p2}}, {add_ln840_15_fu_2914_p2}}, {add_ln840_7_fu_2900_p2}};

assign p_Result_s_fu_303_p1 = in0_V_TDATA[0:0];

assign select_ln272_1_fu_2829_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_8_7154_fu_248);

assign select_ln272_2_fu_2836_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_7_7152_fu_244);

assign select_ln272_3_fu_2843_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_6_7150_fu_240);

assign select_ln272_4_fu_2850_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_5_7148_fu_236);

assign select_ln272_5_fu_2857_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_4_7146_fu_232);

assign select_ln272_6_fu_2864_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_3_7144_fu_228);

assign select_ln272_7_fu_2871_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_2_7142_fu_224);

assign select_ln272_8_fu_2878_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_1_7140_fu_220);

assign select_ln272_9_fu_2885_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_775138_fu_216);

assign select_ln272_fu_2822_p3 = ((icmp_ln272_reg_3190[0:0] == 1'b1) ? 7'd0 : add_i_i_i2_9_7156_fu_252);

assign sf_1_fu_2765_p2 = (ap_sig_allocacmp_sf_load + 32'd1);

assign xor_ln1019_100_fu_1901_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_50_fu_1821_p3);

assign xor_ln1019_101_fu_1907_p2 = (xor_ln1019_100_fu_1901_p2 ^ 1'd1);

assign xor_ln1019_102_fu_1917_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_51_fu_1829_p3);

assign xor_ln1019_103_fu_1923_p2 = (xor_ln1019_102_fu_1917_p2 ^ 1'd1);

assign xor_ln1019_104_fu_1933_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_52_fu_1837_p3);

assign xor_ln1019_105_fu_1939_p2 = (xor_ln1019_104_fu_1933_p2 ^ 1'd1);

assign xor_ln1019_106_fu_1949_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_53_fu_1845_p3);

assign xor_ln1019_107_fu_1955_p2 = (xor_ln1019_106_fu_1949_p2 ^ 1'd1);

assign xor_ln1019_108_fu_1965_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_54_fu_1853_p3);

assign xor_ln1019_109_fu_1971_p2 = (xor_ln1019_108_fu_1965_p2 ^ 1'd1);

assign xor_ln1019_10_fu_493_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_5_fu_349_p3);

assign xor_ln1019_110_fu_1981_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_55_fu_1861_p3);

assign xor_ln1019_111_fu_1987_p2 = (xor_ln1019_110_fu_1981_p2 ^ 1'd1);

assign xor_ln1019_112_fu_2109_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_56_fu_2045_p3);

assign xor_ln1019_113_fu_2115_p2 = (xor_ln1019_112_fu_2109_p2 ^ 1'd1);

assign xor_ln1019_114_fu_2125_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_57_fu_2053_p3);

assign xor_ln1019_115_fu_2131_p2 = (xor_ln1019_114_fu_2125_p2 ^ 1'd1);

assign xor_ln1019_116_fu_2141_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_58_fu_2061_p3);

assign xor_ln1019_117_fu_2147_p2 = (xor_ln1019_116_fu_2141_p2 ^ 1'd1);

assign xor_ln1019_118_fu_2157_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_59_fu_2069_p3);

assign xor_ln1019_119_fu_2163_p2 = (xor_ln1019_118_fu_2157_p2 ^ 1'd1);

assign xor_ln1019_11_fu_499_p2 = (xor_ln1019_10_fu_493_p2 ^ 1'd1);

assign xor_ln1019_120_fu_2173_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_60_fu_2077_p3);

assign xor_ln1019_121_fu_2179_p2 = (xor_ln1019_120_fu_2173_p2 ^ 1'd1);

assign xor_ln1019_122_fu_2189_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_61_fu_2085_p3);

assign xor_ln1019_123_fu_2195_p2 = (xor_ln1019_122_fu_2189_p2 ^ 1'd1);

assign xor_ln1019_124_fu_2205_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_62_fu_2093_p3);

assign xor_ln1019_125_fu_2211_p2 = (xor_ln1019_124_fu_2205_p2 ^ 1'd1);

assign xor_ln1019_126_fu_2221_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_63_fu_2101_p3);

assign xor_ln1019_127_fu_2227_p2 = (xor_ln1019_126_fu_2221_p2 ^ 1'd1);

assign xor_ln1019_128_fu_2349_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_64_fu_2285_p3);

assign xor_ln1019_129_fu_2355_p2 = (xor_ln1019_128_fu_2349_p2 ^ 1'd1);

assign xor_ln1019_12_fu_517_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_6_fu_357_p3);

assign xor_ln1019_130_fu_2365_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_65_fu_2293_p3);

assign xor_ln1019_131_fu_2371_p2 = (xor_ln1019_130_fu_2365_p2 ^ 1'd1);

assign xor_ln1019_132_fu_2381_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_66_fu_2301_p3);

assign xor_ln1019_133_fu_2387_p2 = (xor_ln1019_132_fu_2381_p2 ^ 1'd1);

assign xor_ln1019_134_fu_2397_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_67_fu_2309_p3);

assign xor_ln1019_135_fu_2403_p2 = (xor_ln1019_134_fu_2397_p2 ^ 1'd1);

assign xor_ln1019_136_fu_2413_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_68_fu_2317_p3);

assign xor_ln1019_137_fu_2419_p2 = (xor_ln1019_136_fu_2413_p2 ^ 1'd1);

assign xor_ln1019_138_fu_2429_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_69_fu_2325_p3);

assign xor_ln1019_139_fu_2435_p2 = (xor_ln1019_138_fu_2429_p2 ^ 1'd1);

assign xor_ln1019_13_fu_523_p2 = (xor_ln1019_12_fu_517_p2 ^ 1'd1);

assign xor_ln1019_140_fu_2445_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_70_fu_2333_p3);

assign xor_ln1019_141_fu_2451_p2 = (xor_ln1019_140_fu_2445_p2 ^ 1'd1);

assign xor_ln1019_142_fu_2461_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_71_fu_2341_p3);

assign xor_ln1019_143_fu_2467_p2 = (xor_ln1019_142_fu_2461_p2 ^ 1'd1);

assign xor_ln1019_144_fu_2589_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_72_fu_2525_p3);

assign xor_ln1019_145_fu_2595_p2 = (xor_ln1019_144_fu_2589_p2 ^ 1'd1);

assign xor_ln1019_146_fu_2605_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_73_fu_2533_p3);

assign xor_ln1019_147_fu_2611_p2 = (xor_ln1019_146_fu_2605_p2 ^ 1'd1);

assign xor_ln1019_148_fu_2621_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_74_fu_2541_p3);

assign xor_ln1019_149_fu_2627_p2 = (xor_ln1019_148_fu_2621_p2 ^ 1'd1);

assign xor_ln1019_14_fu_541_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_7_fu_365_p3);

assign xor_ln1019_150_fu_2637_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_75_fu_2549_p3);

assign xor_ln1019_151_fu_2643_p2 = (xor_ln1019_150_fu_2637_p2 ^ 1'd1);

assign xor_ln1019_152_fu_2653_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_76_fu_2557_p3);

assign xor_ln1019_153_fu_2659_p2 = (xor_ln1019_152_fu_2653_p2 ^ 1'd1);

assign xor_ln1019_154_fu_2669_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_77_fu_2565_p3);

assign xor_ln1019_155_fu_2675_p2 = (xor_ln1019_154_fu_2669_p2 ^ 1'd1);

assign xor_ln1019_156_fu_2685_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_78_fu_2573_p3);

assign xor_ln1019_157_fu_2691_p2 = (xor_ln1019_156_fu_2685_p2 ^ 1'd1);

assign xor_ln1019_158_fu_2701_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_79_fu_2581_p3);

assign xor_ln1019_159_fu_2707_p2 = (xor_ln1019_158_fu_2701_p2 ^ 1'd1);

assign xor_ln1019_15_fu_547_p2 = (xor_ln1019_14_fu_541_p2 ^ 1'd1);

assign xor_ln1019_16_fu_669_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_8_fu_605_p3);

assign xor_ln1019_17_fu_675_p2 = (xor_ln1019_16_fu_669_p2 ^ 1'd1);

assign xor_ln1019_18_fu_685_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_9_fu_613_p3);

assign xor_ln1019_19_fu_691_p2 = (xor_ln1019_18_fu_685_p2 ^ 1'd1);

assign xor_ln1019_1_fu_379_p2 = (xor_ln1019_fu_373_p2 ^ 1'd1);

assign xor_ln1019_20_fu_701_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_10_fu_621_p3);

assign xor_ln1019_21_fu_707_p2 = (xor_ln1019_20_fu_701_p2 ^ 1'd1);

assign xor_ln1019_22_fu_717_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_11_fu_629_p3);

assign xor_ln1019_23_fu_723_p2 = (xor_ln1019_22_fu_717_p2 ^ 1'd1);

assign xor_ln1019_24_fu_733_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_12_fu_637_p3);

assign xor_ln1019_25_fu_739_p2 = (xor_ln1019_24_fu_733_p2 ^ 1'd1);

assign xor_ln1019_26_fu_749_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_13_fu_645_p3);

assign xor_ln1019_27_fu_755_p2 = (xor_ln1019_26_fu_749_p2 ^ 1'd1);

assign xor_ln1019_28_fu_765_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_14_fu_653_p3);

assign xor_ln1019_29_fu_771_p2 = (xor_ln1019_28_fu_765_p2 ^ 1'd1);

assign xor_ln1019_2_fu_397_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_1_fu_317_p3);

assign xor_ln1019_30_fu_781_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_15_fu_661_p3);

assign xor_ln1019_31_fu_787_p2 = (xor_ln1019_30_fu_781_p2 ^ 1'd1);

assign xor_ln1019_32_fu_909_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_16_fu_845_p3);

assign xor_ln1019_33_fu_915_p2 = (xor_ln1019_32_fu_909_p2 ^ 1'd1);

assign xor_ln1019_34_fu_925_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_17_fu_853_p3);

assign xor_ln1019_35_fu_931_p2 = (xor_ln1019_34_fu_925_p2 ^ 1'd1);

assign xor_ln1019_36_fu_941_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_18_fu_861_p3);

assign xor_ln1019_37_fu_947_p2 = (xor_ln1019_36_fu_941_p2 ^ 1'd1);

assign xor_ln1019_38_fu_957_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_19_fu_869_p3);

assign xor_ln1019_39_fu_963_p2 = (xor_ln1019_38_fu_957_p2 ^ 1'd1);

assign xor_ln1019_3_fu_403_p2 = (xor_ln1019_2_fu_397_p2 ^ 1'd1);

assign xor_ln1019_40_fu_973_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_20_fu_877_p3);

assign xor_ln1019_41_fu_979_p2 = (xor_ln1019_40_fu_973_p2 ^ 1'd1);

assign xor_ln1019_42_fu_989_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_21_fu_885_p3);

assign xor_ln1019_43_fu_995_p2 = (xor_ln1019_42_fu_989_p2 ^ 1'd1);

assign xor_ln1019_44_fu_1005_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_22_fu_893_p3);

assign xor_ln1019_45_fu_1011_p2 = (xor_ln1019_44_fu_1005_p2 ^ 1'd1);

assign xor_ln1019_46_fu_1021_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_23_fu_901_p3);

assign xor_ln1019_47_fu_1027_p2 = (xor_ln1019_46_fu_1021_p2 ^ 1'd1);

assign xor_ln1019_48_fu_1149_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_24_fu_1085_p3);

assign xor_ln1019_49_fu_1155_p2 = (xor_ln1019_48_fu_1149_p2 ^ 1'd1);

assign xor_ln1019_4_fu_421_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_2_fu_325_p3);

assign xor_ln1019_50_fu_1165_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_25_fu_1093_p3);

assign xor_ln1019_51_fu_1171_p2 = (xor_ln1019_50_fu_1165_p2 ^ 1'd1);

assign xor_ln1019_52_fu_1181_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_26_fu_1101_p3);

assign xor_ln1019_53_fu_1187_p2 = (xor_ln1019_52_fu_1181_p2 ^ 1'd1);

assign xor_ln1019_54_fu_1197_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_27_fu_1109_p3);

assign xor_ln1019_55_fu_1203_p2 = (xor_ln1019_54_fu_1197_p2 ^ 1'd1);

assign xor_ln1019_56_fu_1213_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_28_fu_1117_p3);

assign xor_ln1019_57_fu_1219_p2 = (xor_ln1019_56_fu_1213_p2 ^ 1'd1);

assign xor_ln1019_58_fu_1229_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_29_fu_1125_p3);

assign xor_ln1019_59_fu_1235_p2 = (xor_ln1019_58_fu_1229_p2 ^ 1'd1);

assign xor_ln1019_5_fu_427_p2 = (xor_ln1019_4_fu_421_p2 ^ 1'd1);

assign xor_ln1019_60_fu_1245_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_30_fu_1133_p3);

assign xor_ln1019_61_fu_1251_p2 = (xor_ln1019_60_fu_1245_p2 ^ 1'd1);

assign xor_ln1019_62_fu_1261_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_31_fu_1141_p3);

assign xor_ln1019_63_fu_1267_p2 = (xor_ln1019_62_fu_1261_p2 ^ 1'd1);

assign xor_ln1019_64_fu_1389_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_32_fu_1325_p3);

assign xor_ln1019_65_fu_1395_p2 = (xor_ln1019_64_fu_1389_p2 ^ 1'd1);

assign xor_ln1019_66_fu_1405_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_33_fu_1333_p3);

assign xor_ln1019_67_fu_1411_p2 = (xor_ln1019_66_fu_1405_p2 ^ 1'd1);

assign xor_ln1019_68_fu_1421_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_34_fu_1341_p3);

assign xor_ln1019_69_fu_1427_p2 = (xor_ln1019_68_fu_1421_p2 ^ 1'd1);

assign xor_ln1019_6_fu_445_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_3_fu_333_p3);

assign xor_ln1019_70_fu_1437_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_35_fu_1349_p3);

assign xor_ln1019_71_fu_1443_p2 = (xor_ln1019_70_fu_1437_p2 ^ 1'd1);

assign xor_ln1019_72_fu_1453_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_36_fu_1357_p3);

assign xor_ln1019_73_fu_1459_p2 = (xor_ln1019_72_fu_1453_p2 ^ 1'd1);

assign xor_ln1019_74_fu_1469_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_37_fu_1365_p3);

assign xor_ln1019_75_fu_1475_p2 = (xor_ln1019_74_fu_1469_p2 ^ 1'd1);

assign xor_ln1019_76_fu_1485_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_38_fu_1373_p3);

assign xor_ln1019_77_fu_1491_p2 = (xor_ln1019_76_fu_1485_p2 ^ 1'd1);

assign xor_ln1019_78_fu_1501_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_39_fu_1381_p3);

assign xor_ln1019_79_fu_1507_p2 = (xor_ln1019_78_fu_1501_p2 ^ 1'd1);

assign xor_ln1019_7_fu_451_p2 = (xor_ln1019_6_fu_445_p2 ^ 1'd1);

assign xor_ln1019_80_fu_1629_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_40_fu_1565_p3);

assign xor_ln1019_81_fu_1635_p2 = (xor_ln1019_80_fu_1629_p2 ^ 1'd1);

assign xor_ln1019_82_fu_1645_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_41_fu_1573_p3);

assign xor_ln1019_83_fu_1651_p2 = (xor_ln1019_82_fu_1645_p2 ^ 1'd1);

assign xor_ln1019_84_fu_1661_p2 = (p_Result_2_fu_413_p3 ^ local_temp_V_42_fu_1581_p3);

assign xor_ln1019_85_fu_1667_p2 = (xor_ln1019_84_fu_1661_p2 ^ 1'd1);

assign xor_ln1019_86_fu_1677_p2 = (p_Result_3_fu_437_p3 ^ local_temp_V_43_fu_1589_p3);

assign xor_ln1019_87_fu_1683_p2 = (xor_ln1019_86_fu_1677_p2 ^ 1'd1);

assign xor_ln1019_88_fu_1693_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_44_fu_1597_p3);

assign xor_ln1019_89_fu_1699_p2 = (xor_ln1019_88_fu_1693_p2 ^ 1'd1);

assign xor_ln1019_8_fu_469_p2 = (p_Result_4_fu_461_p3 ^ local_temp_V_4_fu_341_p3);

assign xor_ln1019_90_fu_1709_p2 = (p_Result_5_fu_485_p3 ^ local_temp_V_45_fu_1605_p3);

assign xor_ln1019_91_fu_1715_p2 = (xor_ln1019_90_fu_1709_p2 ^ 1'd1);

assign xor_ln1019_92_fu_1725_p2 = (p_Result_6_fu_509_p3 ^ local_temp_V_46_fu_1613_p3);

assign xor_ln1019_93_fu_1731_p2 = (xor_ln1019_92_fu_1725_p2 ^ 1'd1);

assign xor_ln1019_94_fu_1741_p2 = (p_Result_7_fu_533_p3 ^ local_temp_V_47_fu_1621_p3);

assign xor_ln1019_95_fu_1747_p2 = (xor_ln1019_94_fu_1741_p2 ^ 1'd1);

assign xor_ln1019_96_fu_1869_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_48_fu_1805_p3);

assign xor_ln1019_97_fu_1875_p2 = (xor_ln1019_96_fu_1869_p2 ^ 1'd1);

assign xor_ln1019_98_fu_1885_p2 = (p_Result_1_fu_389_p3 ^ local_temp_V_49_fu_1813_p3);

assign xor_ln1019_99_fu_1891_p2 = (xor_ln1019_98_fu_1885_p2 ^ 1'd1);

assign xor_ln1019_9_fu_475_p2 = (xor_ln1019_8_fu_469_p2 ^ 1'd1);

assign xor_ln1019_fu_373_p2 = (p_Result_s_fu_303_p1 ^ local_temp_V_fu_313_p1);

assign zext_ln1019_10_fu_985_p1 = xor_ln1019_41_fu_979_p2;

assign zext_ln1019_11_fu_1017_p1 = xor_ln1019_45_fu_1011_p2;

assign zext_ln1019_12_fu_1161_p1 = xor_ln1019_49_fu_1155_p2;

assign zext_ln1019_13_fu_1177_p1 = xor_ln1019_51_fu_1171_p2;

assign zext_ln1019_14_fu_1193_p1 = xor_ln1019_53_fu_1187_p2;

assign zext_ln1019_15_fu_1209_p1 = xor_ln1019_55_fu_1203_p2;

assign zext_ln1019_16_fu_1225_p1 = xor_ln1019_57_fu_1219_p2;

assign zext_ln1019_17_fu_1257_p1 = xor_ln1019_61_fu_1251_p2;

assign zext_ln1019_18_fu_1401_p1 = xor_ln1019_65_fu_1395_p2;

assign zext_ln1019_19_fu_1417_p1 = xor_ln1019_67_fu_1411_p2;

assign zext_ln1019_1_fu_697_p1 = xor_ln1019_19_fu_691_p2;

assign zext_ln1019_20_fu_1433_p1 = xor_ln1019_69_fu_1427_p2;

assign zext_ln1019_21_fu_1449_p1 = xor_ln1019_71_fu_1443_p2;

assign zext_ln1019_22_fu_1465_p1 = xor_ln1019_73_fu_1459_p2;

assign zext_ln1019_23_fu_1497_p1 = xor_ln1019_77_fu_1491_p2;

assign zext_ln1019_24_fu_1641_p1 = xor_ln1019_81_fu_1635_p2;

assign zext_ln1019_25_fu_1657_p1 = xor_ln1019_83_fu_1651_p2;

assign zext_ln1019_26_fu_1673_p1 = xor_ln1019_85_fu_1667_p2;

assign zext_ln1019_27_fu_1689_p1 = xor_ln1019_87_fu_1683_p2;

assign zext_ln1019_28_fu_1705_p1 = xor_ln1019_89_fu_1699_p2;

assign zext_ln1019_29_fu_1737_p1 = xor_ln1019_93_fu_1731_p2;

assign zext_ln1019_2_fu_713_p1 = xor_ln1019_21_fu_707_p2;

assign zext_ln1019_30_fu_1881_p1 = xor_ln1019_97_fu_1875_p2;

assign zext_ln1019_31_fu_1897_p1 = xor_ln1019_99_fu_1891_p2;

assign zext_ln1019_32_fu_1913_p1 = xor_ln1019_101_fu_1907_p2;

assign zext_ln1019_33_fu_1929_p1 = xor_ln1019_103_fu_1923_p2;

assign zext_ln1019_34_fu_1945_p1 = xor_ln1019_105_fu_1939_p2;

assign zext_ln1019_35_fu_1977_p1 = xor_ln1019_109_fu_1971_p2;

assign zext_ln1019_36_fu_2121_p1 = xor_ln1019_113_fu_2115_p2;

assign zext_ln1019_37_fu_2137_p1 = xor_ln1019_115_fu_2131_p2;

assign zext_ln1019_38_fu_2153_p1 = xor_ln1019_117_fu_2147_p2;

assign zext_ln1019_39_fu_2169_p1 = xor_ln1019_119_fu_2163_p2;

assign zext_ln1019_3_fu_729_p1 = xor_ln1019_23_fu_723_p2;

assign zext_ln1019_40_fu_2185_p1 = xor_ln1019_121_fu_2179_p2;

assign zext_ln1019_41_fu_2217_p1 = xor_ln1019_125_fu_2211_p2;

assign zext_ln1019_42_fu_2361_p1 = xor_ln1019_129_fu_2355_p2;

assign zext_ln1019_43_fu_2377_p1 = xor_ln1019_131_fu_2371_p2;

assign zext_ln1019_44_fu_2393_p1 = xor_ln1019_133_fu_2387_p2;

assign zext_ln1019_45_fu_2409_p1 = xor_ln1019_135_fu_2403_p2;

assign zext_ln1019_46_fu_2425_p1 = xor_ln1019_137_fu_2419_p2;

assign zext_ln1019_47_fu_2457_p1 = xor_ln1019_141_fu_2451_p2;

assign zext_ln1019_48_fu_2601_p1 = xor_ln1019_145_fu_2595_p2;

assign zext_ln1019_49_fu_2617_p1 = xor_ln1019_147_fu_2611_p2;

assign zext_ln1019_4_fu_745_p1 = xor_ln1019_25_fu_739_p2;

assign zext_ln1019_50_fu_2633_p1 = xor_ln1019_149_fu_2627_p2;

assign zext_ln1019_51_fu_2649_p1 = xor_ln1019_151_fu_2643_p2;

assign zext_ln1019_52_fu_2665_p1 = xor_ln1019_153_fu_2659_p2;

assign zext_ln1019_53_fu_2697_p1 = xor_ln1019_157_fu_2691_p2;

assign zext_ln1019_5_fu_777_p1 = xor_ln1019_29_fu_771_p2;

assign zext_ln1019_6_fu_921_p1 = xor_ln1019_33_fu_915_p2;

assign zext_ln1019_7_fu_937_p1 = xor_ln1019_35_fu_931_p2;

assign zext_ln1019_8_fu_953_p1 = xor_ln1019_37_fu_947_p2;

assign zext_ln1019_9_fu_969_p1 = xor_ln1019_39_fu_963_p2;

assign zext_ln1019_fu_681_p1 = xor_ln1019_17_fu_675_p2;

assign zext_ln780_1_fu_409_p1 = xor_ln1019_3_fu_403_p2;

assign zext_ln780_2_fu_433_p1 = xor_ln1019_5_fu_427_p2;

assign zext_ln780_3_fu_457_p1 = xor_ln1019_7_fu_451_p2;

assign zext_ln780_4_fu_481_p1 = xor_ln1019_9_fu_475_p2;

assign zext_ln780_5_fu_529_p1 = xor_ln1019_13_fu_523_p2;

assign zext_ln780_fu_385_p1 = xor_ln1019_1_fu_379_p2;

assign zext_ln840_10_fu_835_p1 = add_ln840_13_fu_829_p2;

assign zext_ln840_11_fu_2911_p1 = add_ln840_14_reg_3219;

assign zext_ln840_12_fu_1001_p1 = xor_ln1019_43_fu_995_p2;

assign zext_ln840_13_fu_1033_p1 = xor_ln1019_47_fu_1027_p2;

assign zext_ln840_14_fu_1043_p1 = add_ln840_17_fu_1037_p2;

assign zext_ln840_15_fu_1059_p1 = add_ln840_19_fu_1053_p2;

assign zext_ln840_16_fu_1075_p1 = add_ln840_21_fu_1069_p2;

assign zext_ln840_17_fu_2925_p1 = add_ln840_22_reg_3229;

assign zext_ln840_18_fu_1241_p1 = xor_ln1019_59_fu_1235_p2;

assign zext_ln840_19_fu_1273_p1 = xor_ln1019_63_fu_1267_p2;

assign zext_ln840_1_fu_553_p1 = xor_ln1019_15_fu_547_p2;

assign zext_ln840_20_fu_1283_p1 = add_ln840_25_fu_1277_p2;

assign zext_ln840_21_fu_1299_p1 = add_ln840_27_fu_1293_p2;

assign zext_ln840_22_fu_1315_p1 = add_ln840_29_fu_1309_p2;

assign zext_ln840_23_fu_2939_p1 = add_ln840_30_reg_3239;

assign zext_ln840_24_fu_1481_p1 = xor_ln1019_75_fu_1475_p2;

assign zext_ln840_25_fu_1513_p1 = xor_ln1019_79_fu_1507_p2;

assign zext_ln840_26_fu_1523_p1 = add_ln840_33_fu_1517_p2;

assign zext_ln840_27_fu_1539_p1 = add_ln840_35_fu_1533_p2;

assign zext_ln840_28_fu_1555_p1 = add_ln840_37_fu_1549_p2;

assign zext_ln840_29_fu_2953_p1 = add_ln840_38_reg_3249;

assign zext_ln840_2_fu_563_p1 = add_ln840_1_fu_557_p2;

assign zext_ln840_30_fu_1721_p1 = xor_ln1019_91_fu_1715_p2;

assign zext_ln840_31_fu_1753_p1 = xor_ln1019_95_fu_1747_p2;

assign zext_ln840_32_fu_1763_p1 = add_ln840_41_fu_1757_p2;

assign zext_ln840_33_fu_1779_p1 = add_ln840_43_fu_1773_p2;

assign zext_ln840_34_fu_1795_p1 = add_ln840_45_fu_1789_p2;

assign zext_ln840_35_fu_2967_p1 = add_ln840_46_reg_3259;

assign zext_ln840_36_fu_1961_p1 = xor_ln1019_107_fu_1955_p2;

assign zext_ln840_37_fu_1993_p1 = xor_ln1019_111_fu_1987_p2;

assign zext_ln840_38_fu_2003_p1 = add_ln840_49_fu_1997_p2;

assign zext_ln840_39_fu_2019_p1 = add_ln840_51_fu_2013_p2;

assign zext_ln840_3_fu_579_p1 = add_ln840_3_fu_573_p2;

assign zext_ln840_40_fu_2035_p1 = add_ln840_53_fu_2029_p2;

assign zext_ln840_41_fu_2981_p1 = add_ln840_54_reg_3269;

assign zext_ln840_42_fu_2201_p1 = xor_ln1019_123_fu_2195_p2;

assign zext_ln840_43_fu_2233_p1 = xor_ln1019_127_fu_2227_p2;

assign zext_ln840_44_fu_2243_p1 = add_ln840_57_fu_2237_p2;

assign zext_ln840_45_fu_2259_p1 = add_ln840_59_fu_2253_p2;

assign zext_ln840_46_fu_2275_p1 = add_ln840_61_fu_2269_p2;

assign zext_ln840_47_fu_2995_p1 = add_ln840_62_reg_3279;

assign zext_ln840_48_fu_2441_p1 = xor_ln1019_139_fu_2435_p2;

assign zext_ln840_49_fu_2473_p1 = xor_ln1019_143_fu_2467_p2;

assign zext_ln840_4_fu_595_p1 = add_ln840_5_fu_589_p2;

assign zext_ln840_50_fu_2483_p1 = add_ln840_65_fu_2477_p2;

assign zext_ln840_51_fu_2499_p1 = add_ln840_67_fu_2493_p2;

assign zext_ln840_52_fu_2515_p1 = add_ln840_69_fu_2509_p2;

assign zext_ln840_53_fu_3009_p1 = add_ln840_70_reg_3289;

assign zext_ln840_54_fu_2681_p1 = xor_ln1019_155_fu_2675_p2;

assign zext_ln840_55_fu_2713_p1 = xor_ln1019_159_fu_2707_p2;

assign zext_ln840_56_fu_2723_p1 = add_ln840_73_fu_2717_p2;

assign zext_ln840_57_fu_2739_p1 = add_ln840_75_fu_2733_p2;

assign zext_ln840_58_fu_2755_p1 = add_ln840_77_fu_2749_p2;

assign zext_ln840_59_fu_3023_p1 = add_ln840_78_reg_3299;

assign zext_ln840_5_fu_2897_p1 = add_ln840_6_reg_3209;

assign zext_ln840_6_fu_761_p1 = xor_ln1019_27_fu_755_p2;

assign zext_ln840_7_fu_793_p1 = xor_ln1019_31_fu_787_p2;

assign zext_ln840_8_fu_803_p1 = add_ln840_9_fu_797_p2;

assign zext_ln840_9_fu_819_p1 = add_ln840_11_fu_813_p2;

assign zext_ln840_fu_505_p1 = xor_ln1019_11_fu_499_p2;

endmodule //MatrixVectorActivation_3_Matrix_Vector_Activate_Stream_Batch
