# This file was automatically generated by Vpl
# utilization reports
report_utilization_impl true "finn_design instrumentation_wrapper" "placed" "" $input_dir $vivado_output_dir
collect_compute_unit_utilization ""
