
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xinstrumentation_wrapper.h"

/*
* The configuration table for devices
*/

XInstrumentation_wrapper_Config XInstrumentation_wrapper_ConfigTable[XPAR_XINSTRUMENTATION_WRAPPER_NUM_INSTANCES] =
{
	{
		XPAR_INSTRUMENTATION_WRAPPER_0_DEVICE_ID,
		XPAR_INSTRUMENTATION_WRAPPER_0_S_AXI_CTRL_BASEADDR
	}
};


