# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.runs/synth_1/vmk180_thin_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param project.enablePRFlowIPI 1
set_param bd.debug_profile.script /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/.local/debug_profile_automation.tcl
set_param bd.enable_dpa 1
set_param project.loadTopLevelOOCConstrs 1
set_param bd.clkrstAutomationV2 1
set_param project.gatelevelSubdesign 1
set_param place.ultrathreadsUsed 0
set_param hd.Visual 0
set_param general.maxThreads 1
set_param bd.ForceAppCoreUpgrade 1
set_param compiler.enablePerformanceTrace 1
set_param chipscope.flow 0
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvm1802-vsva2197-2MP-e-S
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/.local/hw_platform/board} [current_project]
set_property board_part xilinx.com:vmk180:part0:3.1 [current_project]
set_property ip_repo_paths {
  /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/int/xo/ip_repo/xilinx_com_hls_instrumentation_wrapper_1_0
  /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/int/xo/ip_repo/xilinx_finn_finn_finn_design_1_0
  /proj/xbuilds/SWIP/2022.2_1014_8888/installs/lin64/Vitis/2022.2/data/cache/xilinx
  /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/.local/hw_platform/ipcache
  /proj/xbuilds/SWIP/2022.2_1014_8888/installs/lin64/Vitis/2022.2/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/hdl/vmk180_thin_wrapper.v
add_files /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.srcs/sources_1/bd/vmk180_thin/vmk180_thin.bd
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_CIPS_0_0/bd_0/ip/ip_0/bd_4ac6_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_CIPS_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_CIPS_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_CIPS_0_0/bd_0/bd_4ac6_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_axi_intc_0_0/vmk180_thin_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_axi_intc_0_0/vmk180_thin_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_axi_intc_0_0/vmk180_thin_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_clk_wizard_0_0/vmk180_thin_clk_wizard_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_clk_wizard_0_0/vmk180_thin_clk_wizard_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_clk_wizard_0_0/vmk180_thin_clk_wizard_0_0_late.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_clk_wizard_0_0/vmk180_thin_clk_wizard_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_proc_sys_reset_0_0/vmk180_thin_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_proc_sys_reset_0_0/vmk180_thin_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_proc_sys_reset_0_0/vmk180_thin_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_1/bd_4d5f_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_1/bd_4d5f_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_2/bd_4d5f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_2/bd_4d5f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_3/bd_4d5f_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_3/bd_4d5f_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_4/bd_4d5f_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_5/bd_4d5f_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_6/bd_4d5f_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_7/bd_4d5f_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_8/bd_4d5f_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_9/bd_4d5f_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_10/bd_4d5f_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_11/bd_4d5f_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_12/bd_4d5f_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_13/bd_4d5f_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_14/bd_4d5f_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_15/bd_4d5f_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_16/bd_4d5f_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_17/bd_4d5f_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_18/bd_4d5f_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_22/bd_4d5f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_23/bd_4d5f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_24/bd_4d5f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_25/bd_4d5f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_26/bd_4d5f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_27/bd_4d5f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_28/bd_4d5f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_29/bd_4d5f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_30/bd_4d5f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_31/bd_4d5f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_32/bd_4d5f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_33/bd_4d5f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_35/bd_4d5f_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_36/bd_4d5f_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_37/bd_4d5f_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_38/bd_4d5f_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_39/bd_4d5f_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/bd_0/ip/ip_40/bd_4d5f_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_icn_ctrl_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_finn_design_0_0/vmk180_thin_finn_design_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_instrumentation_wrapper_0_0/constraints/instrumentation_wrapper_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_rst_clk_wizard_0_303M_0/vmk180_thin_rst_clk_wizard_0_303M_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_rst_clk_wizard_0_303M_0/vmk180_thin_rst_clk_wizard_0_303M_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/ip/vmk180_thin_rst_clk_wizard_0_303M_0/vmk180_thin_rst_clk_wizard_0_303M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/vmk180_thin_ooc.xdc]
set_property used_in_synthesis false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/nsln/vmk180_thin.nts]
set_property used_in_implementation false [get_files -all /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/prj/prj.gen/sources_1/bd/vmk180_thin/nsln/vmk180_thin.nts]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/output/vmk180_thin_ooc_copy.xdc
set_property used_in_implementation false [get_files /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/output/vmk180_thin_ooc_copy.xdc]
set_property processing_order EARLY [get_files /scratch/hannayan/finn_instr_wrap_test/finn/tests/performance/instr_wrap_platform_v2/instr_wrap_build/vitis/_x/link/vivado/vpl/output/vmk180_thin_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top vmk180_thin_wrapper -part xcvm1802-vsva2197-2MP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vmk180_thin_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
